/**
 * Asset Preview Bubble Component
 *
 * Displays streaming asset previews with syntax highlighting.
 * Shows content incrementally as it's generated by the agent.
 * Supports expand/collapse for long content.
 *
 * PERFORMANCE: No typewriter animation. Uses <pre> during streaming
 * and when collapsed. SyntaxHighlighter only when expanded + complete.
 */

import { useState, useRef, memo, useCallback, lazy, Suspense } from 'react';
import {
  FileCode,
  FileJson,
  MessageSquare,
  Workflow,
  Boxes,
  Building2,
  Settings,
  CheckCircle2,
  Copy,
  Check,
  Loader2,
  Search,
  FileText,
  Package,
  ChevronDown,
  ChevronRight,
  Download,
  RefreshCw,
  ClipboardCheck,
} from 'lucide-react';
import { cn } from '../lib/utils';
import { ContactFlowPreview } from './ContactFlowPreview';
import { MermaidDiagram } from './MermaidDiagram';
import { generatePresignedUrl } from '../services/sessions';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { AssetPreview } from '../types';
import { DiffPreview } from './DiffPreview';

// Lazy-load SyntaxHighlighter - only loaded when user expands a completed asset
const SyntaxHighlighter = lazy(() =>
  import('react-syntax-highlighter/dist/esm/prism-light').then(mod => ({ default: mod.default }))
);
let oneDarkStyle: any = null;
import('react-syntax-highlighter/dist/esm/styles/prism/one-dark').then(mod => { oneDarkStyle = mod.default; });

// Asset type display info with collapse behavior
const ASSET_TYPE_INFO: Record<string, {
  icon: React.ReactNode;
  label: string;
  labelKo: string;
  color: string;
  collapseMode: 'title-only' | 'preview' | 'full';
  previewLines?: number;
}> = {
  lambda: { icon: <FileCode className="w-4 h-4" />, label: 'Lambda Function', labelKo: 'Lambda 함수', color: 'text-orange-600 bg-orange-50 border-orange-200', collapseMode: 'preview', previewLines: 8 },
  openapi: { icon: <FileJson className="w-4 h-4" />, label: 'OpenAPI Spec', labelKo: 'OpenAPI 스펙', color: 'text-blue-600 bg-blue-50 border-blue-200', collapseMode: 'preview', previewLines: 10 },
  prompt: { icon: <MessageSquare className="w-4 h-4" />, label: 'AI Prompt', labelKo: 'AI 프롬프트', color: 'text-purple-600 bg-purple-50 border-purple-200', collapseMode: 'preview', previewLines: 8 },
  contact_flow: { icon: <Workflow className="w-4 h-4" />, label: 'Contact Flow', labelKo: 'Contact Flow', color: 'text-green-600 bg-green-50 border-green-200', collapseMode: 'full' },
  mermaid: { icon: <Workflow className="w-4 h-4" />, label: 'Flow Diagram', labelKo: '플로우 다이어그램', color: 'text-violet-600 bg-violet-50 border-violet-200', collapseMode: 'full' },
  cdk: { icon: <Boxes className="w-4 h-4" />, label: 'CloudFormation Template', labelKo: 'CloudFormation 템플릿', color: 'text-cyan-600 bg-cyan-50 border-cyan-200', collapseMode: 'preview', previewLines: 10 },
  cloudformation: { icon: <Boxes className="w-4 h-4" />, label: 'CloudFormation Template', labelKo: 'CloudFormation 템플릿', color: 'text-cyan-600 bg-cyan-50 border-cyan-200', collapseMode: 'preview', previewLines: 10 },
  company: { icon: <Building2 className="w-4 h-4" />, label: 'Company Profile', labelKo: '회사 정보', color: 'text-indigo-600 bg-indigo-50 border-indigo-200', collapseMode: 'full' },
  operations: { icon: <Settings className="w-4 h-4" />, label: 'Operations', labelKo: '작업 정의', color: 'text-teal-600 bg-teal-50 border-teal-200', collapseMode: 'full' },
  validation: { icon: <CheckCircle2 className="w-4 h-4" />, label: 'Validation Rules', labelKo: '유효성 검사', color: 'text-amber-600 bg-amber-50 border-amber-200', collapseMode: 'full' },
  research: { icon: <Search className="w-4 h-4" />, label: 'Research Result', labelKo: '리서치 결과', color: 'text-sky-600 bg-sky-50 border-sky-200', collapseMode: 'preview', previewLines: 6 },
  faq: { icon: <FileText className="w-4 h-4" />, label: 'FAQ Document', labelKo: 'FAQ 문서', color: 'text-emerald-600 bg-emerald-50 border-emerald-200', collapseMode: 'title-only' },
  package: { icon: <Package className="w-4 h-4" />, label: 'Knowledge Base Package', labelKo: 'Knowledge Base 패키지', color: 'text-rose-600 bg-rose-50 border-rose-200', collapseMode: 'full' },
  review: { icon: <ClipboardCheck className="w-4 h-4" />, label: 'Review Report', labelKo: '리뷰 리포트', color: 'text-red-600 bg-red-50 border-red-200', collapseMode: 'full' },
  operation_spec: { icon: <ClipboardCheck className="w-4 h-4" />, label: 'Operation Spec', labelKo: 'Operation 정의', color: 'text-teal-600 bg-teal-50 border-teal-200', collapseMode: 'full' },
  workspace_file: { icon: <FileCode className="w-4 h-4" />, label: 'Workspace File', labelKo: '워크스페이스 파일', color: 'text-amber-600 bg-amber-50 border-amber-200', collapseMode: 'preview', previewLines: 12 },
  requirement: { icon: <FileText className="w-4 h-4" />, label: 'Parsed Requirements', labelKo: '파싱된 요구사항', color: 'text-sky-600 bg-sky-50 border-sky-200', collapseMode: 'preview', previewLines: 12 },
};

interface AssetPreviewBubbleProps {
  preview: AssetPreview;
  language?: string;
}

export const AssetPreviewBubble = memo(function AssetPreviewBubble({ preview, language = 'ko-KR' }: AssetPreviewBubbleProps) {
  // Delegate to specialized components
  if (preview.assetType === 'contact_flow') {
    return <ContactFlowPreview preview={preview} language={language} />;
  }

  if (preview.assetType === 'mermaid') {
    // Detect lazy-loading state: s3Key exists but content not yet loaded from S3
    const isLazyLoading = !!(preview.s3Key && !preview.content);
    return (
      <div className="rounded-lg border border-violet-200 bg-violet-50 p-4">
        <div className="flex items-center gap-2 mb-3 text-violet-600">
          <Workflow className="w-4 h-4" />
          <span className="text-sm font-medium">
            {language === 'ko-KR' ? '플로우 다이어그램' : 'Flow Diagram'}
          </span>
          {(!preview.isComplete || isLazyLoading) && <Loader2 className="w-4 h-4 animate-spin ml-auto" />}
        </div>
        <div className="bg-white rounded-lg p-4 border border-violet-100">
          {preview.isComplete && !isLazyLoading ? (
            (() => {
              const mermaidCode = preview.content
                .replace(/^#[^\n]*\n\n?/, '')
                .replace(/^```mermaid\n?/, '')
                .replace(/\n?```\s*$/, '');
              return <MermaidDiagram chart={mermaidCode} language={language} />;
            })()
          ) : (
            <div className="flex flex-col items-center justify-center py-8 text-gray-500">
              <Loader2 className="w-8 h-8 animate-spin mb-3" />
              <span className="text-sm">
                {isLazyLoading
                  ? (language === 'ko-KR' ? '다이어그램 로딩 중...' : 'Loading diagram...')
                  : (language === 'ko-KR' ? '다이어그램 생성 중...' : 'Generating diagram...')}
              </span>
            </div>
          )}
        </div>
      </div>
    );
  }

  const [copied, setCopied] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [viewMode, setViewMode] = useState<'compare' | 'new' | 'previous'>('compare');
  // Diff tab: default to 'diff' when diffContent is available, otherwise 'code'
  const [contentTab, setContentTab] = useState<'code' | 'diff'>(preview.diffContent ? 'diff' : 'code');
  const contentRef = useRef<HTMLDivElement>(null);

  const typeInfo = ASSET_TYPE_INFO[preview.assetType] || {
    icon: <FileText className="w-4 h-4" />, label: preview.assetType || 'Asset', labelKo: preview.assetType || '에셋',
    color: 'text-gray-600 bg-gray-50 border-gray-200', collapseMode: 'preview' as const, previewLines: 8,
  };
  const displayLabel = language === 'ko-KR' ? typeInfo.labelKo : typeInfo.label;

  const shouldCollapse = typeInfo.collapseMode !== 'full';
  const isTitleOnly = typeInfo.collapseMode === 'title-only';
  const previewLines = typeInfo.previewLines || 8;

  // Detect lazy-loading state for generic assets: s3Key exists but content not yet loaded
  const isGenericLazyLoading = !!(preview.s3Key && !preview.content);

  // Content directly from preview - no typewriter animation
  const content = preview.content;
  const lines = content.split('\n');
  const totalLines = lines.length;
  const needsCollapse = shouldCollapse && totalLines > previewLines;

  const getDisplayContent = () => {
    if (!shouldCollapse || isExpanded) return content;
    if (isTitleOnly) return '';
    return lines.slice(0, previewLines).join('\n');
  };

  const displayContent = getDisplayContent();
  const showContent = !isTitleOnly || isExpanded;
  const isStreaming = !preview.isComplete;

  // Only use SyntaxHighlighter when expanded AND complete (expensive render)
  const useSyntaxHighlighting = isExpanded && preview.isComplete && !isStreaming;

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(preview.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [preview.content]);

  const handleDownload = useCallback(async () => {
    if (!preview.s3Key) return;
    setIsDownloading(true);
    try {
      const userSub = localStorage.getItem('aicc-user-sub') || '';
      const sessionId = localStorage.getItem(`aicc-current-session-${userSub}`) ||
                        localStorage.getItem(`aicc-session-id-${userSub}`) || '';
      if (!sessionId) return;
      const result = await generatePresignedUrl(sessionId, preview.s3Key);
      if (result.success && result.downloadUrl) window.open(result.downloadUrl, '_blank');
    } finally {
      setIsDownloading(false);
    }
  }, [preview.s3Key]);

  const getSyntaxLanguage = () => {
    if (preview.language) return preview.language;
    if (preview.fileName) {
      if (preview.fileName.endsWith('.py')) return 'python';
      if (preview.fileName.endsWith('.ts')) return 'typescript';
      if (preview.fileName.endsWith('.js')) return 'javascript';
      if (preview.fileName.endsWith('.json')) return 'json';
      if (preview.fileName.endsWith('.yaml') || preview.fileName.endsWith('.yml')) return 'yaml';
      if (preview.fileName.endsWith('.md')) return 'markdown';
    }
    switch (preview.assetType) {
      case 'lambda': return 'python';
      case 'openapi': return 'yaml';
      case 'prompt': return 'markdown';
      case 'contact_flow': return 'json';
      case 'cdk': case 'cloudformation': return 'yaml';
      case 'research': case 'faq': case 'package': case 'operation_spec': case 'requirement': return 'markdown';
      default: return 'text';
    }
  };

  return (
    <div className="animate-fade-in my-3">
      <div className={cn('w-full rounded-2xl border overflow-hidden', typeInfo.color)}>
        {/* Header */}
        <div
          className={cn(
            "flex items-center justify-between px-4 py-3 border-b border-inherit",
            shouldCollapse && "cursor-pointer hover:bg-white/20 transition-colors"
          )}
          onClick={shouldCollapse ? () => setIsExpanded(!isExpanded) : undefined}
        >
          <div className="flex items-center gap-2">
            {shouldCollapse && (
              <div className="w-5 h-5 flex items-center justify-center">
                {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
              </div>
            )}
            <div className={cn('w-8 h-8 rounded-full flex items-center justify-center', preview.isComplete ? 'bg-white/80' : 'bg-white/50')}>
              {isStreaming ? <Loader2 className="w-4 h-4 animate-spin" /> : preview.isRegeneration ? <RefreshCw className="w-4 h-4" /> : typeInfo.icon}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-medium text-sm">{displayLabel}</span>
                {preview.assetType === 'workspace_file' && preview.operationId ? (
                  <span className={cn('text-xs px-1.5 py-0.5 rounded-full',
                    preview.operationId === 'write' ? 'bg-green-100 text-green-700' :
                    preview.operationId === 'patch' ? 'bg-blue-100 text-blue-700' :
                    'bg-yellow-100 text-yellow-700')}>
                    {preview.operationId === 'write' ? (language === 'ko-KR' ? '생성' : 'Created') :
                     preview.operationId === 'patch' ? (language === 'ko-KR' ? '수정' : 'Modified') :
                     (language === 'ko-KR' ? '추가' : 'Appended')}
                  </span>
                ) : preview.operationId ? (
                  <span className="text-xs opacity-70 font-mono">({preview.operationId})</span>
                ) : null}
                {preview.isRegeneration && (
                  <span className="inline-flex items-center gap-1 px-1.5 py-0.5 text-xs bg-amber-100 text-amber-700 rounded-full">
                    <RefreshCw className="w-3 h-3" />
                    {language === 'ko-KR' ? '재생성됨' : 'Regenerated'}
                  </span>
                )}
              </div>
              {preview.fileName && <span className="text-xs opacity-70 font-mono">{preview.fileName}</span>}
            </div>
          </div>

          <div className="flex items-center gap-1" onClick={(e) => e.stopPropagation()}>
            {shouldCollapse && !isExpanded && <span className="text-xs opacity-60 mr-2">{totalLines} {language === 'ko-KR' ? '줄' : 'lines'}</span>}
            <button onClick={handleCopy} className="p-1.5 rounded-md transition-colors hover:bg-white/50 text-current opacity-70 hover:opacity-100" title={language === 'ko-KR' ? '복사' : 'Copy'}>
              {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
            </button>
            {preview.isComplete && preview.s3Key && (
              <button onClick={handleDownload} disabled={isDownloading} className="p-1.5 rounded-md transition-colors hover:bg-white/50 text-current opacity-70 hover:opacity-100" title={language === 'ko-KR' ? '다운로드' : 'Download'}>
                {isDownloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              </button>
            )}
          </div>
        </div>

        {/* View mode tabs for regenerated assets */}
        {preview.isRegeneration && preview.previousContent && preview.isComplete && (
          <div className="px-4 py-2 bg-white/20 border-b border-inherit flex items-center gap-2">
            <span className="text-xs opacity-70 mr-2">{language === 'ko-KR' ? '보기:' : 'View:'}</span>
            <div className="flex gap-1 border rounded-lg p-0.5 bg-white/50">
              {(['compare', 'new', 'previous'] as const).map(mode => (
                <button key={mode} onClick={() => setViewMode(mode)}
                  className={cn("px-2 py-1 text-xs rounded transition-colors", viewMode === mode ? "bg-white shadow-sm font-medium" : "hover:bg-white/50 opacity-70")}>
                  {mode === 'compare' ? (language === 'ko-KR' ? '비교' : 'Compare') : mode === 'new' ? (language === 'ko-KR' ? '새 버전' : 'New') : (language === 'ko-KR' ? '이전' : 'Previous')}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Diff / Code tabs for workspace file modifications */}
        {preview.diffContent && preview.isComplete && !preview.isRegeneration && (
          <div className="px-4 py-2 bg-white/20 border-b border-inherit flex items-center gap-2">
            <span className="text-xs opacity-70 mr-2">{language === 'ko-KR' ? '보기:' : 'View:'}</span>
            <div className="flex gap-1 border rounded-lg p-0.5 bg-white/50">
              {(['diff', 'code'] as const).map(tab => (
                <button key={tab} onClick={() => setContentTab(tab)}
                  className={cn("px-2 py-1 text-xs rounded transition-colors", contentTab === tab ? "bg-white shadow-sm font-medium" : "hover:bg-white/50 opacity-70")}>
                  {tab === 'diff' ? (language === 'ko-KR' ? '변경사항' : 'Changes') : (language === 'ko-KR' ? '전체 코드' : 'Full Code')}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Content */}
        {showContent && isGenericLazyLoading && (
          <div className="flex flex-col items-center justify-center py-8 text-gray-500">
            <Loader2 className="w-6 h-6 animate-spin mb-2" />
            <span className="text-xs">{language === 'ko-KR' ? '콘텐츠 로딩 중...' : 'Loading content...'}</span>
          </div>
        )}
        {/* Diff view (shown when diff tab is active) */}
        {showContent && !isGenericLazyLoading && preview.diffContent && contentTab === 'diff' && preview.isComplete && (
          <div ref={contentRef} className={cn("relative overflow-auto", isExpanded ? "max-h-[70vh]" : needsCollapse ? "max-h-[200px]" : "max-h-[70vh]")}>
            <DiffPreview diffContent={preview.diffContent} />
            {needsCollapse && !isExpanded && !isTitleOnly && (
              <div className="absolute bottom-0 left-0 right-0 h-12 pointer-events-none" style={{ background: 'linear-gradient(transparent, rgba(0,0,0,0.85))' }} />
            )}
          </div>
        )}

        {/* Code view (original content rendering) */}
        {showContent && !isGenericLazyLoading && !(preview.diffContent && contentTab === 'diff' && preview.isComplete) && (
          <div ref={contentRef} className={cn("relative overflow-auto", isExpanded ? "max-h-[70vh]" : needsCollapse ? "max-h-[200px]" : "max-h-[70vh]")}>
            {isStreaming && (
              <div className="absolute top-2 right-2 z-10">
                <div className="flex items-center gap-2 text-xs bg-white/90 px-2 py-1 rounded-full shadow-sm">
                  <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                  <span className="text-gray-600">{language === 'ko-KR' ? '생성 중...' : 'Generating...'}</span>
                </div>
              </div>
            )}

            {/* Rich markdown rendering for review reports, operation specs, and requirements */}
            {(preview.assetType === 'review' || preview.assetType === 'operation_spec' || preview.assetType === 'requirement') ? (
              <div className="p-5 prose prose-sm max-w-none
                prose-headings:text-gray-800 prose-h1:text-lg prose-h1:border-b prose-h1:pb-2 prose-h1:mb-4
                prose-h2:text-base prose-h2:mt-5 prose-h2:mb-2
                prose-h3:text-sm prose-h3:mt-3
                prose-p:text-gray-700 prose-p:my-1.5
                prose-li:text-gray-700 prose-li:my-0.5
                prose-table:text-xs prose-th:bg-gray-100 prose-th:px-3 prose-th:py-1.5 prose-td:px-3 prose-td:py-1.5 prose-td:border-gray-200
                prose-code:text-teal-700 prose-code:bg-teal-50 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:text-xs
                prose-strong:text-gray-900
                bg-white text-gray-800">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{displayContent}</ReactMarkdown>
                {isStreaming && <span className="inline-block w-2 h-4 bg-teal-400 animate-pulse ml-1" />}
              </div>
            ) : preview.isRegeneration && preview.previousContent && viewMode === 'compare' && !isStreaming && useSyntaxHighlighting ? (
              <Suspense fallback={<pre className="p-4 text-sm font-mono text-gray-100 whitespace-pre-wrap" style={{ background: 'rgba(0,0,0,0.85)' }}>{displayContent}</pre>}>
                <div className="grid grid-cols-2 divide-x divide-gray-700">
                  <div className="flex flex-col">
                    <div className="px-3 py-1.5 bg-gray-800 text-xs text-gray-400 font-medium border-b border-gray-700">
                      {language === 'ko-KR' ? '이전 버전' : 'Previous Version'}
                    </div>
                    <SyntaxHighlighter language={getSyntaxLanguage()} style={oneDarkStyle || {}} customStyle={{ margin: 0, borderRadius: 0, fontSize: '0.75rem', background: 'rgba(0,0,0,0.85)', flex: 1 }} showLineNumbers wrapLines>
                      {preview.previousContent}
                    </SyntaxHighlighter>
                  </div>
                  <div className="flex flex-col">
                    <div className="px-3 py-1.5 bg-gray-800 text-xs text-green-400 font-medium border-b border-gray-700">
                      {language === 'ko-KR' ? '새 버전' : 'New Version'}
                    </div>
                    <SyntaxHighlighter language={getSyntaxLanguage()} style={oneDarkStyle || {}} customStyle={{ margin: 0, borderRadius: 0, fontSize: '0.75rem', background: 'rgba(0,0,0,0.85)', flex: 1 }} showLineNumbers wrapLines>
                      {displayContent}
                    </SyntaxHighlighter>
                  </div>
                </div>
              </Suspense>
            ) : useSyntaxHighlighting ? (
              /* Full syntax highlighting only when expanded + complete */
              <Suspense fallback={<pre className="p-4 text-sm font-mono text-gray-100 whitespace-pre-wrap" style={{ background: 'rgba(0,0,0,0.85)' }}>{displayContent}</pre>}>
                <SyntaxHighlighter
                  language={getSyntaxLanguage()}
                  style={oneDarkStyle || {}}
                  customStyle={{ margin: 0, borderRadius: 0, fontSize: '0.8rem', background: 'rgba(0,0,0,0.85)' }}
                  showLineNumbers wrapLines
                >
                  {preview.isRegeneration && viewMode === 'previous' && preview.previousContent ? preview.previousContent : displayContent}
                </SyntaxHighlighter>
              </Suspense>
            ) : (
              /* Lightweight <pre> for streaming, collapsed preview, or not-yet-expanded */
              <pre
                className="p-4 text-sm font-mono text-gray-100 whitespace-pre-wrap break-words"
                style={{ margin: 0, background: 'rgba(0,0,0,0.85)', minHeight: isStreaming ? '100px' : undefined }}
              >
                {displayContent}
                {isStreaming && <span className="animate-pulse">▊</span>}
              </pre>
            )}

            {needsCollapse && !isExpanded && !isTitleOnly && (
              <div className="absolute bottom-0 left-0 right-0 h-12 pointer-events-none" style={{ background: 'linear-gradient(transparent, rgba(0,0,0,0.85))' }} />
            )}
          </div>
        )}

        {/* Footer */}
        <div className="px-4 py-2 bg-white/30 border-t border-inherit flex items-center justify-between text-xs">
          <span className="opacity-70">
            {totalLines} {language === 'ko-KR' ? '줄' : 'lines'}
            {needsCollapse && !isExpanded && (
              <span className="ml-1 opacity-60">
                ({language === 'ko-KR' ? `${previewLines}줄 미리보기` : `showing ${previewLines} lines`})
              </span>
            )}
          </span>
          <div className="flex items-center gap-3">
            {(needsCollapse || isTitleOnly) && (
              <button onClick={() => setIsExpanded(!isExpanded)} className="flex items-center gap-1 text-current opacity-70 hover:opacity-100 transition-opacity">
                {isExpanded ? <><ChevronDown className="w-3 h-3" />{language === 'ko-KR' ? '접기' : 'Collapse'}</> : <><ChevronRight className="w-3 h-3" />{language === 'ko-KR' ? '펼치기' : 'Expand'}</>}
              </button>
            )}
            {preview.isComplete && (
              <span className="flex items-center gap-1 text-green-600">
                <CheckCircle2 className="w-3 h-3" />
                {language === 'ko-KR' ? '완료' : 'Complete'}
              </span>
            )}
            {isStreaming && (
              <span className="text-gray-500">{content.length} chars</span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
});

export default AssetPreviewBubble;
