/**
 * Mermaid Diagram Component
 *
 * Renders Mermaid.js diagrams from markdown code blocks.
 * Used primarily for visualizing Contact Flow diagrams.
 */

import { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import { AlertCircle, RefreshCw } from 'lucide-react';
import { cn } from '../lib/utils';

// Initialize mermaid with configuration
mermaid.initialize({
  startOnLoad: false,
  theme: 'base',
  securityLevel: 'strict',
  flowchart: {
    useMaxWidth: false,
    htmlLabels: true,
    curve: 'basis',
    padding: 15,
    nodeSpacing: 30,
    rankSpacing: 40,
  },
  themeVariables: {
    primaryColor: '#E8F5E9',
    primaryTextColor: '#1a1a1a',
    primaryBorderColor: '#4CAF50',
    lineColor: '#666',
    secondaryColor: '#E3F2FD',
    tertiaryColor: '#f5f5f5',
    fontSize: '13px',
    nodeBorder: '#4CAF50',
    mainBkg: '#E8F5E9',
    edgeLabelBackground: '#fff',
  },
});

/**
 * Sanitize mermaid chart content to fix common syntax issues
 * generated by LLMs:
 * 1. Replace hyphens in node IDs with underscores
 * 2. Remove special characters from node IDs
 * 3. Fix parentheses used as node brackets
 */
function sanitizeMermaidChart(chart: string): string {
  let sanitized = chart;

  // Split into lines for processing
  const lines = sanitized.split('\n');
  const processedLines = lines.map(line => {
    // Skip lines that are just comments or empty
    if (line.trim().startsWith('%%') || line.trim() === '') {
      return line;
    }

    // Fix node definitions with hyphens: node-id[Label] → node_id[Label]
    // Match: word-word pattern followed by [ or { or ( or --> or space
    line = line.replace(/\b([a-zA-Z][a-zA-Z0-9]*)-([a-zA-Z][a-zA-Z0-9_-]*)\b(?=[\[\{\(>\s]|$)/g, '$1_$2');

    // Fix remaining hyphens in node IDs (recursive for multi-hyphen names)
    let prevLine = '';
    while (prevLine !== line) {
      prevLine = line;
      line = line.replace(/\b([a-zA-Z_][a-zA-Z0-9_]*)-([a-zA-Z][a-zA-Z0-9_]*)\b(?=[\[\{\(>\s]|$)/g, '$1_$2');
    }

    // Fix parentheses used for nodes: (Label) → [Label]
    // But only if it looks like a node definition (not already a bracket or brace)
    // Pattern: nodeId(Label) where nodeId is followed by parentheses
    line = line.replace(/\b([a-zA-Z_][a-zA-Z0-9_]*)\(([^)]+)\)(?=\s*(?:-->|$|\s))/g, '$1[$2]');

    // Remove @ and # from node IDs (not from labels)
    line = line.replace(/\b([a-zA-Z_][a-zA-Z0-9_]*)[@#]([a-zA-Z0-9_]*)\b(?=[\[\{\(>\s]|$)/g, '$1_$2');

    return line;
  });

  return processedLines.join('\n');
}

interface MermaidDiagramProps {
  chart: string;
  className?: string;
  language?: string;
}

export function MermaidDiagram({ chart, className, language = 'ko-KR' }: MermaidDiagramProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [key, setKey] = useState(0);

  useEffect(() => {
    const renderDiagram = async () => {
      if (!chart) {
        setError('No chart content provided');
        setIsLoading(false);
        return;
      }

      setIsLoading(true);
      setError(null);

      try {
        const id = `mermaid-${crypto.randomUUID()}`;

        // Clean the chart content (remove markdown code fence if present)
        let cleanChart = chart.trim();

        if (cleanChart.startsWith('```mermaid')) {
          cleanChart = cleanChart.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '');
        } else if (cleanChart.startsWith('```')) {
          cleanChart = cleanChart.replace(/^```\w*\n?/, '').replace(/\n?```$/, '');
        }

        // Sanitize the chart to fix common LLM syntax issues
        cleanChart = sanitizeMermaidChart(cleanChart);

        // Ensure flowchart has a direction; default to TD (top-down) if unspecified
        if (cleanChart.match(/^(flowchart|graph)\s*$/m)) {
          cleanChart = cleanChart.replace(/^(flowchart|graph)\s*$/m, '$1 TD');
        }

        const { svg: renderedSvg } = await mermaid.render(id, cleanChart);
        // SECURITY — dangerouslySetInnerHTML justification:
        //   The `svg` string injected below is produced by mermaid.render() which
        //   is initialized with `securityLevel: 'strict'` (see mermaid.initialize
        //   above). In 'strict' mode Mermaid HTML-escapes all user-controlled
        //   text, forbids raw HTML tags / <script> / event handlers in labels,
        //   and sanitizes the generated SVG before returning it. This matches
        //   Mermaid's documented XSS defense:
        //     https://mermaid.js.org/config/usage.html#securitylevel
        //   We deliberately do NOT post-sanitize with DOMPurify here because
        //   DOMPurify strips <foreignObject> and inline <style> nodes that
        //   Mermaid relies on for htmlLabels and theming, which breaks every
        //   flowchart we render. DOMPurify is still used for non-Mermaid HTML
        //   surfaces (see AssetPreviewBubble, ContactFlowPreview).
        setSvg(renderedSvg);
      } catch (err) {
        console.error('[MermaidDiagram] Rendering error:', err);
        const errorMessage = err instanceof Error ? err.message : String(err);
        let helpText = '';
        if (errorMessage.includes('Syntax error') || errorMessage.includes('Parse error')) {
          helpText = ' - Check for invalid characters in node IDs (use only letters, numbers, underscores)';
        } else if (errorMessage.includes('Expecting')) {
          helpText = ' - Check for malformed arrows or missing node definitions';
        }
        setError(errorMessage + helpText);
      } finally {
        setIsLoading(false);
      }
    };

    renderDiagram();
  }, [chart, key]);

  const handleRetry = () => {
    setKey(prev => prev + 1);
  };

  if (isLoading) {
    return (
      <div className={cn('flex items-center justify-center p-8 bg-gray-50 rounded-lg', className)}>
        <div className="flex items-center gap-2 text-gray-500">
          <RefreshCw className="w-5 h-5 animate-spin" />
          <span>{language === 'ko-KR' ? '다이어그램 렌더링 중...' : 'Rendering diagram...'}</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={cn('p-4 bg-red-50 border border-red-200 rounded-lg', className)}>
        <div className="flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-sm font-medium text-red-800">
              {language === 'ko-KR' ? '다이어그램 렌더링 실패' : 'Failed to render diagram'}
            </p>
            <p className="text-xs text-red-600 mt-1 font-mono">{error}</p>
            <button
              onClick={handleRetry}
              className="mt-2 text-xs text-red-700 hover:text-red-900 underline flex items-center gap-1"
            >
              <RefreshCw className="w-3 h-3" />
              {language === 'ko-KR' ? '다시 시도' : 'Retry'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={cn(
        'mermaid-container overflow-auto bg-white rounded-lg p-4 min-h-[200px]',
        className
      )}
      style={{ maxHeight: '70vh' }}
      // eslint-disable-next-line react/no-danger -- see SECURITY comment in useEffect: svg is produced by mermaid with securityLevel:'strict'
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

export default MermaidDiagram;
