"""
AICC Builder Agent Tools

These tools enable the AI agent to:
1. Introspect databases to understand schema
2. Generate production-ready Lambda functions
3. Generate OpenAPI specifications
4. Generate AI prompts for Amazon Connect
5. Save and manage operation specifications
6. Package and upload assets to S3 for download
   - Collects assets from S3 that were generated by Sub-Agents
   - Creates ZIP with CloudFormation, Lambda, OpenAPI, Prompt, Contact Flow, FAQ
7. Generate Contact Flows with Mermaid visualization
8. Generate CDK infrastructure code (legacy - prefer CloudFormation via Sub-Agent)

Note: The primary infrastructure generation is now handled by the
infrastructure_generator Sub-Agent which produces CloudFormation YAML templates.
"""

from .db_introspector import introspect_database, convert_to_infrastructure_schema
from .lambda_generator import generate_lambda_function
from .openapi_generator import generate_openapi_spec
from .prompt_generator import generate_ai_prompt
from .spec_manager import save_operation_spec, get_operation_spec, list_operations, get_all_operation_ids, get_all_tool_ids, update_operation_spec, format_operation_summary, save_session_flow_config, get_session_flow_config_tool, save_infrastructure_spec, get_infrastructure_spec_tool, infer_missing_tools
from .asset_packager import package_and_upload_assets
from .contact_flow_generator import (
    generate_contact_flow,
    generate_flow_mermaid_only,
    update_contact_flow_greeting,
)
from .cdk_generator import generate_cdk_infrastructure
from .stream_fallback_asset import stream_fallback_asset
from .merge_infrastructure import merge_infrastructure_fragments
from .merge_openapi import merge_openapi_fragments
from .incremental_streamer import IncrementalCodeStreamer
from .asset_lookup import asset_lookup, get_assets_for_review
from .validate_consistency import validate_parameter_consistency
# replace_asset_field removed — use patch_workspace_file instead

# Export NFS workspace file tools for direct file access
from .workspace_file_tools import (
    read_workspace_file,
    write_workspace_file,
    append_workspace_file,
    list_workspace_dir,
    patch_workspace_file,
    find_workspace_files,
    grep_workspace,
)

# Export streaming callback functions for consistent import across modules
from .streaming_callback import (
    set_streaming_callback,
    clear_streaming_callback,
    get_streaming_callback,
    stream_asset,
    complete_asset,
)

# Export heartbeat utilities for Sub-Agent WebSocket keep-alive
from .heartbeat_utils import (
    HeartbeatManager,
    create_heartbeat_manager,
    DEFAULT_HEARTBEAT_INTERVAL,
)

# Export interview completion tool
from .interview_completion import complete_interview

# Export shared context functions for cross-agent communication
from .shared_context import (
    save_research_context,
    get_research_context,
    get_research_summary,
    save_customer_context,
    get_customer_context,
    save_operation_context,
    get_operations_context,
    save_faq_document as save_faq_to_context,
    get_faq_documents,
    get_full_context,
    get_context_for_generation,
    clear_session_context,
)

__all__ = [
    "introspect_database",
    "convert_to_infrastructure_schema",
    "generate_lambda_function",
    "generate_openapi_spec",
    "generate_ai_prompt",
    "save_operation_spec",
    "get_operation_spec",
    "list_operations",
    "get_all_operation_ids",
    "get_all_tool_ids",
    "update_operation_spec",
    "format_operation_summary",
    "save_session_flow_config",
    "get_session_flow_config_tool",
    "save_infrastructure_spec",
    "get_infrastructure_spec_tool",
    "infer_missing_tools",
    "package_and_upload_assets",
    "generate_contact_flow",
    "generate_flow_mermaid_only",
    "update_contact_flow_greeting",
    "generate_cdk_infrastructure",
    "stream_fallback_asset",
    "merge_infrastructure_fragments",
    "merge_openapi_fragments",
    # Incremental code streaming
    "IncrementalCodeStreamer",
    # Asset lookup
    "asset_lookup",
    "get_assets_for_review",
    # Parameter consistency validation
    "validate_parameter_consistency",
    # NFS workspace file tools
    "read_workspace_file",
    "write_workspace_file",
    "append_workspace_file",
    "list_workspace_dir",
    "patch_workspace_file",
    "find_workspace_files",
    "grep_workspace",
    # Streaming callbacks
    "set_streaming_callback",
    "clear_streaming_callback",
    "get_streaming_callback",
    "stream_asset",
    "complete_asset",
    # Heartbeat utilities
    "HeartbeatManager",
    "create_heartbeat_manager",
    "DEFAULT_HEARTBEAT_INTERVAL",
    # Shared context functions
    "save_research_context",
    "get_research_context",
    "get_research_summary",
    "save_customer_context",
    "get_customer_context",
    "save_operation_context",
    "get_operations_context",
    "save_faq_to_context",
    "get_faq_documents",
    "get_full_context",
    "get_context_for_generation",
    "clear_session_context",
    # Interview completion
    "complete_interview",
]
