"""
Asset Packager Tool

Packages all generated assets from S3 into a ZIP file,
uploads to S3, and returns a presigned URL for download.

This module retrieves assets that were generated by Sub-Agents and saved to S3,
packages them into a downloadable ZIP with the following structure:

{project-name}/
├── README.md                    # Deployment guide
├── cloudformation/              # CloudFormation infrastructure (recommended)
│   └── infrastructure.yaml      # Complete infrastructure template
├── lambda/                      # Individual Lambda functions (reference/modify)
│   └── {operation_id}/
│       └── index.py           # Lambda handler code
├── openapi/
│   └── openapi.yaml             # OpenAPI 3.0 spec for MCP Gateway
├── prompts/
│   └── ai_agent_prompt.yaml       # Amazon Connect AI agent prompt
├── contact-flow/
│   └── contact_flow.json        # Importable contact flow
└── knowledge-base/              # Knowledge Base FAQ (optional)
    └── {category}/
        └── *.txt
"""

import contextvars
import hashlib
import io
import json
import logging
import os
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from botocore.exceptions import ClientError
from strands import tool

from .s3_asset_storage import (
    list_session_assets,
    get_asset_from_s3,
    get_bucket_name,
    get_s3_client,
)

logger = logging.getLogger(__name__)


# Static update-q-session Lambda code (Node.js 18.x)
# Calls UpdateSessionData API to inject customer data into Q in Connect session.
# This is a generic proxy — business-specific fields are passed via Contact Flow LambdaInvocationAttributes.
UPDATE_Q_SESSION_LAMBDA_CODE = r"""const { QConnectClient, UpdateSessionDataCommand } = require('@aws-sdk/client-qconnect');
const { ConnectClient, DescribeContactCommand } = require('@aws-sdk/client-connect');

const qConnectClient = new QConnectClient();
const connectClient = new ConnectClient({ region: process.env.AWS_REGION });

const ContextKeys = {
  AI_ASSISTANT_ID: 'AI_ASSISTANT_ID',
  CONNECT_INSTANCE_ID: 'CONNECT_INSTANCE_ID',
};

const log = (level, message, data) => {
  const logEntry = { level, message };
  if (data) logEntry.params = data;
  console.log(JSON.stringify(logEntry));
};

const getAssistantSessionArn = async (contactId, connectInstanceId) => {
  const command = new DescribeContactCommand({
    ContactId: contactId,
    InstanceId: connectInstanceId,
  });
  const response = await connectClient.send(command);
  if (!response.Contact?.WisdomInfo?.SessionArn) {
    throw new Error(`No wisdom session found for contact ${contactId}.`);
  }
  return response.Contact.WisdomInfo.SessionArn;
};

const getKeyValuePairs = (connectRequest) => {
  const parameters = connectRequest.Details.Parameters;
  const reservedKeys = ['AI_ASSISTANT_ID', 'CONNECT_INSTANCE_ID'];
  const keyValuePairs = [];
  for (const [key, value] of Object.entries(parameters)) {
    if (!reservedKeys.includes(key) && value) {
      keyValuePairs.push({ key, value: { stringValue: String(value) } });
    }
  }
  return keyValuePairs;
};

exports.handler = async (connectRequest) => {
  log('INFO', 'Event', connectRequest);
  const contactId = connectRequest.Details.ContactData.ContactId;
  const aiAssistantId = connectRequest.Details.Parameters[ContextKeys.AI_ASSISTANT_ID]
    ?? process.env[ContextKeys.AI_ASSISTANT_ID];

  if (!contactId || !aiAssistantId) {
    throw new Error('Missing required parameters contactId or aiAssistantId');
  }

  const keyValuePairs = getKeyValuePairs(connectRequest);
  if (keyValuePairs.length === 0) {
    throw new Error('No key value pairs found');
  }

  const connectId = process.env[ContextKeys.CONNECT_INSTANCE_ID];
  if (!connectId) {
    throw new Error('No connect instance id found in environment variables');
  }

  const assistantSessionArn = await getAssistantSessionArn(contactId, connectId);
  const command = new UpdateSessionDataCommand({
    assistantId: aiAssistantId,
    sessionId: assistantSessionArn,
    data: keyValuePairs,
  });
  log('INFO', 'updateSessionCommand', command);
  await qConnectClient.send(command);

  return { statusCode: 200 };
};
"""


# Default presigned URL expiration: 24 hours
DEFAULT_EXPIRATION_SECONDS = 24 * 60 * 60


# Asset type to ZIP folder mapping
ASSET_TYPE_FOLDER_MAP = {
    "cloudformation": "cloudformation",
    "infrastructure": "cloudformation",  # Alias
    "cdk": "cloudformation",  # Legacy alias
    "lambda": "lambda",
    "openapi": "openapi",
    "prompt": "prompts",
    "contact_flow": "contact-flow",
    "contactflow": "contact-flow",  # Alias
    "contact-flow": "contact-flow",  # Alias
    "mermaid": "contact-flow",  # Mermaid diagrams go with contact flow
    "faq": "knowledge-base",
    "knowledge_base": "knowledge-base",  # Alias
    "knowledge-base": "knowledge-base",  # Alias
}

# Raw ACXD assets are rewritten to this stable deployment layout only when the
# session target is ACXD. The Classic loop stays unchanged otherwise.
ACXD_STORAGE_TYPES = frozenset({
    "acxd_flow", "acxd_slot_type", "acxd_data_request", "acxd_guardrail",
    "acxd_knowledge_base", "acxd_application", "acxd_context_variable",
    "acxd_secret", "acxd_deploy_manifest",
})
#: Per-asset download of the ACXD application: `asset_type=acxd` (the progress
#: panel's "ACXD Application" button) selects every stored ACXD resource and
#: lays it out exactly as the full bundle does under assets/acxd/.
ACXD_DOWNLOAD_ALIASES = frozenset({"acxd", "acxd_application", "acxd_app"})
_ACXD_TYPE_FOLDERS = {
    "acxd_flow": "flows",
    "acxd_slot_type": "slot-types",
    "acxd_data_request": "data-requests",
    "acxd_guardrail": "guardrails",
    "acxd_knowledge_base": "knowledge-bases",
    "acxd_secret": "secrets",
}


def _acxd_asset_zip_path(project_name: str, asset_type: str, file_name: str) -> str:
    """Canonical bundle path for one stored ACXD resource (mirrors build_acxd_zip_entries)."""
    kind = asset_type.lower()
    if kind == "acxd_application":
        return f"{project_name}/assets/acxd/application.json"
    if kind == "acxd_context_variable":
        return f"{project_name}/assets/acxd/context-variables.json"
    if kind == "acxd_deploy_manifest":
        return f"{project_name}/deploy-manifest.json"
    folder = _ACXD_TYPE_FOLDERS.get(kind, kind.removeprefix("acxd_").replace("_", "-"))
    return f"{project_name}/assets/acxd/{folder}/{file_name}"


ACXD_RUNNER_FILES = (
    "runner.js", "package.json", "lib/manifest.js", "lib/client.js",
    "lib/state.js", "lib/steps.js",
)
_ACXD_RUNNER_DIR = Path(__file__).resolve().parent.parent / "templates" / "acxd_runner"


class ACXDPackagingError(ValueError):
    """Raised when an ACXD bundle cannot safely be handed to a customer."""


#: The wording of the last deliberate refusal, written for the user at the
#: raise site. The download endpoint shows this text, never the exception —
#: exception text can carry paths and internals that do not belong in a reply.
_LAST_REFUSAL: "contextvars.ContextVar[str]" = contextvars.ContextVar("acxd_packaging_refusal", default="")


def _refuse(reason: str) -> None:
    """Record ``reason`` for the caller's reply and abort packaging."""
    _LAST_REFUSAL.set(str(reason))
    raise ACXDPackagingError(reason)


def _slug(value: Any, fallback: str = "unnamed") -> str:
    """Create a path-safe, Unicode-preserving file stem."""
    value = re.sub(r"[^\w.-]+", "-", str(value or "")).strip(".-")
    return value or fallback


def _acxd_field_patterns(operation_folder: str) -> dict:
    """{input field name: regex} for the OperationSpec whose id or tool id names
    this Lambda folder (spellings compared without case, '_' or '-')."""
    try:
        from tools.spec_manager import get_all_specs
        specs = get_all_specs() or {}
    except Exception:  # pragma: no cover - spec store outage is non-fatal
        return {}

    def norm(value) -> str:
        return re.sub(r"[^a-z0-9]", "", str(value or "").lower())

    wanted = norm(operation_folder)
    for op_id, spec in specs.items():
        names = {norm(op_id), norm(getattr(spec, "operation_id", None))}
        for tool in getattr(spec, "tools", None) or []:
            names.add(norm(getattr(tool, "tool_id", None) or getattr(tool, "name", None)
                           or (tool.get("tool_id") if isinstance(tool, dict) else None)))
        if wanted not in names:
            continue
        patterns = {}
        for field in getattr(spec, "input_fields", None) or []:
            name = getattr(field, "name", None) or (field.get("name") if isinstance(field, dict) else None)
            pattern = getattr(field, "pattern", None) or (field.get("pattern") if isinstance(field, dict) else None)
            if name and isinstance(pattern, str) and pattern:
                patterns[str(name)] = pattern
        return patterns
    return {}


def _acxd_request_types(bundle: dict, operation_folder: str) -> dict:
    """{request field: json type} from the Data Request that calls this Lambda —
    the adapter coerces the slot strings ACXD posts ("예", "2") to these types
    (live 2026-09-17: a boolean consent arrived as "예" and was read as False)."""
    return _acxd_schema_types(bundle, operation_folder, "requestSchema")


def _acxd_response_types(bundle: dict, operation_folder: str) -> dict:
    """{response field: json type} from the Data Request that calls this Lambda.

    The service validates the webhook reply against the Data Request's
    responseSchema; the adapter coerces the handler's values to those types
    (live: totalAmount returned as "45000" failed the reply and the order lookup
    went silent). The request is matched by its URL path (/tools/<operation>)
    or, failing that, by its id."""

    return _acxd_schema_types(bundle, operation_folder, "responseSchema")


def _acxd_schema_types(bundle: dict, operation_folder: str, which: str) -> dict:
    """{field: json type} of one schema of the Data Request that calls this Lambda."""
    def norm(value) -> str:
        return re.sub(r"[^a-z0-9]", "", str(value or "").lower())

    wanted = norm(operation_folder)
    fallback: dict = {}
    for doc in (bundle or {}).get("data_requests") or []:
        if not isinstance(doc, dict):
            continue
        webhook = doc.get("webhook") if isinstance(doc.get("webhook"), dict) else {}
        urls = [webhook.get("url")] + list((webhook.get("urls") or {}).values()) \
            if isinstance(webhook.get("urls"), dict) else [webhook.get("url")]
        paths = [str(u).rstrip("/").rsplit("/", 1)[-1] for u in urls if u]
        schema = doc.get(which) if isinstance(doc.get(which), dict) else {}
        props = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
        types = {str(k): v.get("type") for k, v in props.items() if isinstance(v, dict) and v.get("type")}
        if any(norm(p) == wanted for p in paths):
            return types
        if norm(doc.get("dataRequestId")) == wanted and not fallback:
            fallback = types
    return fallback


def _acxd_slot_patterns(bundle: dict, operation_folder: str) -> dict:
    """{request field: regex} for the Lambda folder's data request(s), taken from
    the attached slots that the data_request node's payload maps onto them."""
    def norm(value) -> str:
        return re.sub(r"[^a-z0-9]", "", str(value or "").lower())

    wanted = norm(operation_folder)
    request_ids = set()
    for document in bundle.get("data_requests") or []:
        url = str(((document or {}).get("webhook") or {}).get("url") or "")
        tail = url.rstrip("/").rsplit("/", 1)[-1] if url else ""
        if wanted and (norm(tail) == wanted or norm(document.get("dataRequestId")) == wanted):
            request_ids.add(document.get("dataRequestId"))
    if not request_ids:
        return {}
    patterns: dict = {}
    for flow in bundle.get("flows") or []:
        if not isinstance(flow, dict):
            continue
        slot_regex = {str(s.get("name")): s.get("regex") for s in (flow.get("slotTypes") or [])
                      if isinstance(s, dict) and s.get("name") and isinstance(s.get("regex"), str)}
        # Built-in date/time slots carry no regex (S9 removes it) but their
        # values still arrive without separators; the canonical shapes let the
        # adapter restore 20260918 → 2026-09-18 and 1000 → 10:00.
        for s in flow.get("slotTypes") or []:
            if not isinstance(s, dict) or not s.get("name"):
                continue
            if not isinstance(s.get("regex"), str):
                if s.get("type") == "NLX.Date":
                    slot_regex.setdefault(str(s["name"]), r"^\d{4}-\d{2}-\d{2}$")
                elif s.get("type") == "NLX.Time":
                    slot_regex.setdefault(str(s["name"]), r"^\d{2}:\d{2}$")
            elif s.get("regex") == "^[0-9]{3,4}$":
                # S9's compact-time capture regex: the adapter must restore HH:MM
                slot_regex[str(s["name"])] = r"^\d{2}:\d{2}$"
        for node in (flow.get("nodes") or {}).values():
            if not isinstance(node, dict) or node.get("type") != "data_request":
                continue
            for entry in node.get("dataRequests") or []:
                if not isinstance(entry, dict) or entry.get("dataRequestId") not in request_ids:
                    continue
                for field, value in (entry.get("payload") or {}).items():
                    match = re.fullmatch(r"\{([A-Za-z_][\w-]*):NLX\.Slot\}", str(value or ""))
                    if match and match.group(1) in slot_regex:
                        patterns.setdefault(str(field), slot_regex[match.group(1)])
    return patterns


def _is_acxd_target(session_id: str) -> bool:
    """Late-load the target contract so old Classic sessions remain unaffected."""
    try:
        from .acxd_flow_spec import is_acxd_target
        return bool(is_acxd_target(session_id))
    except Exception as exc:  # Classic packaging must remain available.
        logger.debug("[packager] ACXD target lookup unavailable: %s", exc)
        return False


def _is_acxd_only_target(session_id: str) -> bool:
    """ACXD only (v3.1): the bundle is the ACXD application and its deploy kit."""
    try:
        from .acxd_flow_spec import is_acxd_only_target
        return bool(is_acxd_only_target(session_id))
    except Exception as exc:
        logger.debug("[packager] ACXD-only target lookup unavailable: %s", exc)
        return False


def _acxd_only_backend_settings(session_id: str) -> dict:
    """{base_url, auth_header, timezone} the interview recorded for the customer's API."""
    try:
        from .acxd_flow_spec import get_acxd_flow_spec
        app = getattr(get_acxd_flow_spec(session_id), "application", None)
    except Exception:  # pragma: no cover - the spec store is optional here
        app = None
    try:
        from .acxd_timezone import business_timezone
        locales = list(getattr(app, "locales", None) or [])
        zone = business_timezone(getattr(app, "timezone", None),
                                 getattr(app, "primary_locale", None) or (locales[0] if locales else None))
    except Exception:  # pragma: no cover - documentation only
        zone = None
    return {
        "base_url": (getattr(app, "backend_base_url", None) or "").rstrip("/") or None,
        "auth_header": (getattr(app, "backend_auth_header", None) or "").strip() or None,
        "timezone": zone,
    }


def _load_acxd_bundle(session_id: str) -> dict:
    from .acxd_bundle import load_acxd_bundle
    return load_acxd_bundle(session_id)


def _format_d9_violation(violation: Any) -> str:
    if isinstance(violation, dict):
        identifier = violation.get("id") or violation.get("code") or "D9"
        message = violation.get("message") or violation.get("error") or str(violation)
        location = violation.get("path") or violation.get("asset")
        return f"{identifier}{f' ({location})' if location else ''}: {message}"
    return str(violation)


def _run_d9_checks(session_id: str, bundle: dict) -> list[str]:
    """Use Task C's D9 helper, falling back before it lands during integration."""
    checker = None
    try:
        from . import validate_consistency
        checker = getattr(validate_consistency, "run_d9_checks", None)
    except Exception as exc:
        logger.debug("[packager] run_d9_checks import unavailable: %s", exc)
    if callable(checker):
        result = checker(session_id)
        if isinstance(result, dict):
            result = (result.get("violations") or result.get("problems")
                      or result.get("issues") or [])
        return [_format_d9_violation(item) for item in (result or [])]

    from .validate_acxd_consistency import validate_acxd_consistency
    spec = None
    try:
        from .acxd_flow_spec import get_acxd_flow_spec
        flow_spec = get_acxd_flow_spec(session_id)
        spec = flow_spec.model_dump() if flow_spec else None
    except Exception as exc:
        logger.debug("[packager] ACXD flow spec unavailable for fallback: %s", exc)
    return [_format_d9_violation(item)
            for item in validate_acxd_consistency(bundle, spec=spec)]


def _prepare_acxd_package(session_id: str, project_name: str) -> tuple[dict, dict, list[str]]:
    from .acxd_manifest_builder import (
        acxd_only_backend,
        build_manifest,
        check_manifest_coverage,
        validate_deploy_manifest,
    )

    bundle = _load_acxd_bundle(session_id)
    external_backend, backend_base_url = acxd_only_backend(session_id)
    if external_backend:
        # ACXD only: the customer wires the Agentic CX block into their own
        # Contact Flow; a stray Contact Flow asset is not part of this bundle.
        bundle["contact_flows"] = []
    # Last deterministic pass: a flow patched after generation (review-round
    # fix, modification request) gets the same runtime contract the generator
    # applies at write time — then D9 judges the result.
    try:
        from .validate_acxd_consistency import normalize_bundle_flows
        spec = None
        try:
            from .acxd_flow_spec import get_acxd_flow_spec
            flow_spec = get_acxd_flow_spec(session_id)
            spec = flow_spec.model_dump() if flow_spec else None
        except Exception as exc:
            logger.debug("[packager] ACXD flow spec unavailable for the contract pass: %s", exc)
        notes = normalize_bundle_flows(bundle, spec)
        if notes:
            logger.info("[packager] runtime contract pass at packaging: %d change(s)", len(notes))
        from .validate_acxd_consistency import normalize_bundle_languages
        for note in normalize_bundle_languages(bundle):
            logger.info("[packager] %s", note)
    except Exception as exc:  # pragma: no cover - never block packaging on the pass
        logger.warning("[packager] runtime contract pass skipped: %s", exc)
    manifest = build_manifest(bundle, project_name=project_name,
                              external_backend=external_backend,
                              backend_base_url=backend_base_url)
    problems = [f"D9: {item}" for item in _run_d9_checks(session_id, bundle)]
    problems.extend(validate_deploy_manifest(manifest))
    problems.extend(check_manifest_coverage(manifest, bundle, external_backend=external_backend))
    return bundle, manifest, problems


def _manifest_file_problems(manifest: dict, bundle_paths: set[str]) -> list[str]:
    """Reject a manifest that references backend files absent from the ZIP."""
    problems: list[str] = []
    for step in manifest.get("steps") or []:
        params = step.get("params") or {}
        if step.get("type") == "deploy-cfn-backend":
            template = params.get("templatePath")
            if template and template not in bundle_paths:
                problems.append(
                    f"manifest deploy-cfn-backend references {template!r}, but the "
                    "bundle has no generated backend template")
        for lambda_dir in params.get("lambdaDirs") or []:
            prefix = lambda_dir.rstrip("/") + "/"
            if not any(item.startswith(prefix) for item in bundle_paths):
                problems.append(
                    f"manifest {step.get('type')!r} references lambda dir {lambda_dir!r}, "
                    "but the bundle has no generated handler")
    return problems


def build_acxd_zip_entries(
    project_name: str,
    bundle: dict,
    manifest: dict,
    spec: Optional[dict] = None,
    extra_files: Optional[dict] = None,
    *,
    external_backend: bool = False,
) -> list[tuple[str, bytes, bool]]:
    """Return ACXD-only archive entries after manifest/coverage validation.

    ``spec`` and ``extra_files`` are accepted for compatibility with the
    retired standalone packager. D9 is session-aware and now runs from the
    unified packager before this helper is called. ``external_backend`` marks
    an ACXD-only (v3.1) manifest, whose coverage rules differ.
    """
    from .acxd_manifest_builder import check_manifest_coverage, validate_deploy_manifest

    problems = validate_deploy_manifest(manifest) + check_manifest_coverage(
        manifest, bundle, external_backend=external_backend)
    if problems:
        _refuse("ACXD manifest is invalid:\n  - " + "\n  - ".join(problems))

    entries: list[tuple[str, bytes, bool]] = []
    seen: set[str] = set()

    def add(relative_path: str, payload: bytes | str, executable: bool = False) -> None:
        if relative_path in seen:
            _refuse(
                f"duplicate ACXD bundle path {relative_path!r}; refusing an ambiguous ZIP")
        seen.add(relative_path)
        entries.append((relative_path,
                        payload.encode("utf-8") if isinstance(payload, str) else payload,
                        executable))

    def add_json(relative_path: str, document: Any) -> None:
        add(relative_path, json.dumps(document, ensure_ascii=False, indent=2) + "\n")

    for index, flow in enumerate(bundle.get("flows") or []):
        add_json(f"assets/acxd/flows/{_slug((flow or {}).get('flowId'), f'flow-{index}')}.json", flow)
    for index, slot_type in enumerate(bundle.get("slot_types") or []):
        add_json(f"assets/acxd/slot-types/{_slug((slot_type or {}).get('slotTypeId'), f'slot-type-{index}')}.json", slot_type)
    for index, data_request in enumerate(bundle.get("data_requests") or []):
        add_json(f"assets/acxd/data-requests/{_slug((data_request or {}).get('dataRequestId'), f'data-request-{index}')}.json", data_request)
    for index, guardrail in enumerate(bundle.get("guardrails") or []):
        add_json(f"assets/acxd/guardrails/{_slug((guardrail or {}).get('name'), f'guardrail-{index}')}.json", guardrail)
    for index, knowledge_base in enumerate(bundle.get("knowledge_bases") or []):
        add_json(f"assets/acxd/knowledge-bases/{_slug((knowledge_base or {}).get('name'), f'knowledge-base-{index}')}.json", knowledge_base)
    for index, secret in enumerate(bundle.get("secrets") or []):
        safe_secret = {key: secret[key] for key in ("name", "description", "valueEnv")
                       if isinstance(secret, dict) and key in secret}
        add_json(f"assets/acxd/secrets/{_slug(safe_secret.get('name'), f'secret-{index}')}.json", safe_secret)

    # Empty context variables are still part of the explicit block contract.
    add_json("assets/acxd/context-variables.json", bundle.get("context_variables") or [])
    if bundle.get("application"):
        add_json("assets/acxd/application.json", bundle["application"])
    for index, contact_flow in enumerate(bundle.get("contact_flows") or []):
        file_name = "contact_flow.json" if index == 0 else f"contact_flow-{index}.json"
        add_json(f"contact-flow/{file_name}", contact_flow)
    add_json("deploy-manifest.json", manifest)

    for relative_path in ACXD_RUNNER_FILES:
        source = _ACXD_RUNNER_DIR / relative_path
        if not source.is_file():
            _refuse(f"static ACXD runner file is missing: {source}")
        add(relative_path, source.read_bytes(), executable=relative_path == "runner.js")
    return entries


def _generate_acxd_readme_section() -> str:
    return """## ACXD runtime target

This bundle targets **Amazon Connect Agentic CX Designer (ACXD)**. Classic
CloudFormation, Lambda, OpenAPI, and Connect Contact Flow assets remain in the
archive; ACXD replaces the Classic Lex, AI Prompt, and AgentCore Gateway phases.

```bash
./deploy.sh --dry-run      # the script detects the ACXD bundle (assets/acxd/) by itself
./deploy.sh                # non-interactive: AUTO_CONFIRM=1 CONNECT_INSTANCE_ID=... ./deploy.sh
./deploy.sh status
./deploy.sh cleanup
```

`--target acxd|classic` is only needed to override the detection.

The script prompts for `ACXD_WORKSPACE_ID` and `ACXD_API_KEY` when needed and
never writes either into the bundle. For external Data Requests it passes the
CloudFormation API Gateway output as `WEBHOOK_URL`. Read `WIRING-GUIDE.md`
after deployment: the Agentic CX block and channel attachment are manual until
AWS publishes a Flow-Language representation for that block.

### Backend contract and authentication (ACXD)

There is no AgentCore Gateway / MCP layer in this target: the application's
Data Requests call the API Gateway of the CloudFormation stack directly
(`{WEBHOOK_URL}/tools/<operation>`). `openapi/openapi.yaml` is the **contract**
those Data Requests and the Lambdas are validated against — it is not imported
into any gateway. Every API method requires the stack's API key
(`ApiKeyRequired: true`); the Data Requests send it as `x-api-key` from the ACXD
secret `BackendApiKey`, which `deploy.sh` creates from the stack's `ApiKeyValue`
output (`ACXD_SECRET_BACKENDAPIKEY`). Nothing is manual and the key is never
written into the bundle. An integration the interview marked `mcp` keeps its own
MCP URL instead.
"""


def _binding_for_contact_flow(contact_flow: dict) -> dict:
    metadata = contact_flow.get("Metadata") if isinstance(contact_flow, dict) else None
    return ((metadata or {}).get("acxdBinding")
            or (contact_flow.get("acxdBinding") if isinstance(contact_flow, dict) else None)
            or {})


def _generate_wiring_guide(bundle: dict) -> str:
    application = bundle.get("application") or {}
    lines = [
        "# Agentic CX block — what is already wired and what is left",
        "",
        "The generated contact flow contains the real Agentic CX block",
        "(`ConnectParticipantWithAgenticCX`, verified from a Connect console export)",
        "with its four outputs wired: Default → the flow's wrap-up (logging →",
        "disconnect), Escalation → hours check / queue transfer, Error → fallback",
        "message, Idle chat timeout → disconnect. At",
        "import `./deploy.sh` fills the block's WorkspaceId and ApplicationId with",
        "the ids it just deployed.",
        "",
        "1. Run `./deploy.sh` (the ACXD bundle is detected automatically) against a **Connect Customer** instance.",
        "2. **Alias.** The block also needs the application alias, an ACXD id the SDK",
        "   does not expose. Either export `ACXD_ALIAS_ID=<alias id>` before running",
        "   `./deploy.sh` (it is written into the block), or open the imported flow",
        "   in the Connect designer and pick the alias in the Agentic CX block's",
        f"   dropdown for application **{application.get('name', 'ACXD application')}**, then publish.",
        "3. Optional: adjust speech engine / audio filler / idle timeout in the block.",
        "   Later actions can read `$.AgenticCX.ContextVariables.<name>`.",
        "4. Attach the flow to the intended phone number (voice) or chat widget.",
        "",
        "## Before you test",
        "",
        "- **Starting from an empty account.** `./deploy.sh` needs three things it",
        "  cannot create for you: a *Connect Customer* instance (Amazon Connect Customer",
        "  console → Add an instance; about four minutes to become active), an agentic",
        "  CX designer workspace (open the instance's admin site → Agentic CX designer →",
        "  the setup walkthrough creates one; its id is under Workspace settings →",
        "  Advanced), and an API key: Admin Hub → Users → *API access* → New user",
        "  (account admin) → Generate API key. The `acxd_live_…` key is shown once and",
        "  contains dots — copy all of it. Export them as `CONNECT_INSTANCE_ID`,",
        "  `ACXD_WORKSPACE_ID` and `ACXD_API_KEY` before running the script.",
        "- **Workspace model.** Knowledge-base answers and generative replies run on the",
        "  generative model configured on the ACXD *workspace*. A workspace without one",
        "  still accepts the deployment and the published knowledge base, but those",
        "  nodes answer nothing — set the model in the workspace settings first.",
        "- **After a redeploy.** When `./deploy.sh` has to replace the application",
        "  deployment (the service refuses to update a deployment in place), the alias",
        "  key changes and the published flow keeps serving the previous build. The",
        "  script prints the new key; run `./deploy.sh --rebind-alias <key>` or pick",
        "  the alias again in the block and publish.",
        "",
    ]
    for contact_flow in bundle.get("contact_flows") or []:
        binding = _binding_for_contact_flow(contact_flow)
        branches = binding.get("branches") or {}
        if branches:
            lines.append("## Generated branch targets")
            for branch in ("Default", "Escalation", "Error", "IdleChatTimeout"):
                if branch in branches:
                    lines.append(f"- **{branch}** → `{branches[branch]}`")
            lines.append("")
    return "\n".join(lines)


#: Deploy script shipped with an ACXD-only bundle (v3.1) — the runner, nothing else.
ACXD_ONLY_DEPLOY_TEMPLATE = "deploy_acxd_only.sh"


def _schema_rows(schema: Any) -> list[tuple[str, str, bool, str]]:
    """(name, type, required, description) for each top-level property."""
    if not isinstance(schema, dict):
        return []
    required = set(schema.get("required") or [])
    rows = []
    for name, prop in (schema.get("properties") or {}).items():
        prop = prop if isinstance(prop, dict) else {}
        kind = str(prop.get("type") or "string")
        if kind == "array" and isinstance(prop.get("items"), dict):
            kind = f"array of {prop['items'].get('type') or 'object'}"
        notes = str(prop.get("description") or "")
        if prop.get("enum"):
            values = ", ".join(str(v) for v in prop["enum"])
            notes = f"{notes}; one of: {values}" if notes else f"one of: {values}"
        rows.append((str(name), kind, name in required, notes.replace("|", "/")))
    return rows


def _external_data_requests(bundle: dict) -> list[dict]:
    return [doc for doc in bundle.get("data_requests") or []
            if isinstance(doc, dict)
            and ((doc.get("webhook") or {}).get("implementation") == "external")]


def _generate_backend_contract(bundle: dict, backend: dict) -> str:
    """BACKEND-CONTRACT.md: what the customer's API must answer (ACXD only).

    Rendered from the Data Requests themselves — the one contract the runtime
    enforces — plus the delivery facts the Classic path's Lambda adapter hides
    (separators stripped from slot values, words for yes/no, a 200-only reply
    validated against the response schema). It is documentation, not an
    OpenAPI document: nothing imports it.
    """
    requests = _external_data_requests(bundle)
    secrets = [s for s in bundle.get("secrets") or [] if isinstance(s, dict) and s.get("name")]
    header = backend.get("auth_header")
    lines = [
        "# Backend API contract",
        "",
        "The application's data requests call **your** API directly. This file lists",
        "every call: the path under the base URL, the JSON body the runtime sends and",
        "the JSON reply it validates. It is generated from `assets/acxd/data-requests/`",
        "— change the data requests (re-run the builder), not this file.",
        "",
        "## Base URL and authentication",
        "",
        "- **Base URL**: `WEBHOOK_URL`, set when you run `./deploy.sh`"
        + (f" (default recorded in the interview: `{backend['base_url']}`)." if backend.get("base_url") else "."),
    ]
    if header and secrets:
        secret = secrets[0]
        lines.append(
            f"- **Authentication**: every request carries the header `{header}`; its value is the "
            f"ACXD secret `{secret['name']}`, created at deploy time from "
            f"`{secret.get('valueEnv') or 'ACXD_SECRET_BACKENDAPIKEY'}` (or `ACXD_SECRET_BACKENDAPIKEY`). "
            "The value is never written into the bundle.")
    else:
        lines.append("- **Authentication**: none. The data requests send no credential header; "
                     "restrict the API another way (network, allow-list) before real use.")
    lines += [
        "",
        "## What every endpoint must do",
        "",
        "1. **Read the fields from the JSON body.** The runtime posts the request fields as one",
        "   JSON object. It may add conversation-context keys; ignore keys you do not use.",
        "2. **Accept both forms of a value.** A generative journey's tool call sends values in",
        "   their schema format, with separators (`010-1111-2222`, `2026-09-16`, `10:00`), while",
        "   a fixed capture step sends a built-in slot value without them (`01011112222`,",
        "   `20260916`, `1000`). A yes/no field arrives as the word in the application's language",
        "   (`예` / `아니요`, `yes` / `no`). Normalise (strip the separators) before you validate.",
        "3. **Always answer HTTP 200 with a JSON body.** A 201/204, or a body that does not match",
        "   the response schema below, sends the conversation down the failure path. The reply",
        "   carries the envelope `success` (boolean, required), `errorCode` and `message`",
        "   (strings, never `null`) plus the fields listed. Numbers must be JSON numbers, not",
        "   strings.",
        "4. **Report business outcomes in the envelope, not the status code.** Not found,",
        "   refused or invalid input is `200` with `success: false`, an `errorCode` and a",
        "   `message`, so the assistant can tell the caller what happened.",
    ]
    zone = backend.get("timezone")
    if zone:
        lines += [
            f"5. **Dates are calendar dates in `{zone}`.** The assistant turns \"today\" and",
            f"   \"tomorrow\" into dates in `{zone}` (the ACXD runtime's own clock runs on",
            "   America/New_York) and sends them as `YYYY-MM-DD`. Check date rules (same-day,",
            "   booking window, cut-off times) against your own calendar in the same zone.",
        ]
    lines += [
        "",
    ]
    if not requests:
        lines += ["This bundle has no external data requests.", ""]
    for doc in requests:
        webhook = doc.get("webhook") or {}
        url = str(webhook.get("url") or "")
        path = url.replace("{WEBHOOK_URL}", "") or "/"
        method = str(webhook.get("method") or "POST").upper()
        lines += [f"## `{doc.get('dataRequestId')}`", ""]
        if doc.get("description"):
            lines += [str(doc["description"]), ""]
        lines += [f"`{method} {{WEBHOOK_URL}}{path}`", ""]
        request_rows = _schema_rows(doc.get("requestSchema"))
        lines += ["Request body:", ""]
        if request_rows:
            lines += ["| Field | Type | Required | Notes |", "|---|---|---|---|"]
            lines += [f"| `{n}` | {t} | {'yes' if r else 'no'} | {d} |" for n, t, r, d in request_rows]
        else:
            lines.append("(no fields)")
        response_rows = _schema_rows(doc.get("responseSchema"))
        lines += ["", "Reply body (HTTP 200):", ""]
        if response_rows:
            lines += ["| Field | Type | Required | Notes |", "|---|---|---|---|"]
            lines += [f"| `{n}` | {t} | {'yes' if r else 'no'} | {d} |" for n, t, r, d in response_rows]
        else:
            lines.append("(envelope only)")
        lines.append("")
    return "\n".join(lines)


def _generate_acxd_only_wiring_guide(bundle: dict) -> str:
    """WIRING-GUIDE.md for an ACXD-only bundle: the customer owns the Contact Flow."""
    application = bundle.get("application") or {}
    name = application.get("name", "the ACXD application")
    context_names = [str(v.get("name") or v.get("key") or "") for v in bundle.get("context_variables") or []
                     if isinstance(v, dict)]
    context_names = [n for n in context_names if n]
    settings = application.get("settings") if isinstance(application.get("settings"), dict) else {}
    codes = settings.get("languageCodes") or application.get("languageCodes") or []
    locale = str(settings.get("languageCode") or application.get("mainLanguageCode")
                 or (codes[0] if codes else "") or "").strip() or "<the application's language code>"
    lines = [
        "# Connecting the application to Amazon Connect",
        "",
        "This bundle ships no Contact Flow. After `./deploy.sh` has deployed the application,",
        "add the Agentic CX block to the flow that should reach it:",
        "",
        "1. In your **Connect Customer** instance open the contact flow (inbound voice or chat).",
        f"2. Before the block, set the contact's language to `{locale}`: a **Set contact attributes**",
        "   block that sets the contact's language (in the flow JSON an `UpdateContactData` action",
        f"   with `LanguageCode: {locale}`). Without it every contact fails with \"NLX Chat Streaming",
        "   Failed\" although the application and its build are fine.",
        "3. Add the **Agentic CX** block where the caller should meet the assistant.",
        f"4. In the block pick the ACXD workspace, the application **{name}** and its alias. The",
        "   alias list shows the deployment `deploy.sh` created under the name ACXD gives it",
        "   (`Production`, even for a deployment to the development environment). Click",
        "   **Confirm** at the bottom of the block panel; without it the block keeps its old values.",
        "5. Wire the block's branches:",
        "   - **Default**: the conversation finished (the assistant said goodbye), usually a",
        "     disconnect.",
        "   - **Escalation**: the assistant handed off to a human; route to your queue transfer",
        "     (hours check, set queue, transfer).",
        "   - **Error**: the application could not run; play a short apology and transfer or",
        "     disconnect.",
        "   - **Idle chat timeout** (chat): disconnect.",
        "6. Publish the flow and attach it to a phone number or chat widget.",
        "",
        "## Things the application relies on",
        "",
        "- **The application speaks.** It greets, collects, answers and says goodbye. Keep the",
        "  Contact Flow silent before the block, except a recording or legal notice you must play,",
        "  or the caller hears two greetings.",
        "- **Workspace model.** Knowledge-base answers and generative replies run on the default",
        "  generative model of the ACXD workspace. Set it before the first contact.",
        "- **After a redeploy.** When a redeploy has to replace the application deployment, its",
        "  alias key changes and the block keeps serving the previous build. Re-select the",
        "  application and alias in the block, click **Confirm** and publish, then check with a",
        "  test chat that the new build answers: re-selecting the same `Production` entry has",
        "  left the block on the previous deployment.",
        "- **Chat response time.** Over a chat contact the block took its Error branch about five",
        "  seconds into a turn whose journey called the backend (the application answered after",
        "  eight). Test the turns that call your API through your own chat entry point before",
        "  going live.",
    ]
    if context_names:
        lines += [
            "",
            "## Context variables",
            "",
            "After the block, later actions can read `$.AgenticCX.ContextVariables.<name>`:",
            "",
        ] + [f"- `{n}`" for n in context_names]
    lines.append("")
    return "\n".join(lines)


def _generate_acxd_only_readme(project_name: str, bundle: dict, manifest: dict, backend: dict) -> str:
    """README.md for an ACXD-only bundle (v3.1)."""
    from .acxd_bundle import bundle_summary

    counts = bundle_summary(bundle)
    application = bundle.get("application") or {}
    has_backend = bool(_external_data_requests(bundle))
    lines = [
        f"# {project_name}",
        "",
        "**Agentic CX Designer application (ACXD only)**",
        "",
        f"Generated by AICC Builder on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
        "This bundle holds only what Agentic CX Designer deploys. There is no CloudFormation,",
        "Lambda, OpenAPI or Contact Flow: the data requests call your existing API, and you add",
        "the Agentic CX block to your own Contact Flow.",
        "",
        "## Contents",
        "",
        f"- `assets/acxd/application.json`: the application **{application.get('name', '')}**",
        f"- `assets/acxd/flows/`: {counts.get('flows', 0)} conversation flow(s)",
        f"- `assets/acxd/data-requests/`: {counts.get('data_requests', 0)} data request(s)",
        f"- `assets/acxd/slot-types/`: {counts.get('slot_types', 0)} slot type(s)",
        f"- `assets/acxd/guardrails/`: {counts.get('guardrails', 0)} guardrail(s)",
        f"- `assets/acxd/knowledge-bases/`: {counts.get('knowledge_bases', 0)} knowledge base(s) with their articles",
        f"- `assets/acxd/secrets/`: {counts.get('secrets', 0)} secret declaration(s) (names only, never values)",
        "- `assets/acxd/context-variables.json`",
        f"- `deploy-manifest.json`: {len(manifest.get('steps') or [])} deploy step(s) run by `runner.js`",
        "- `deploy.sh`, `runner.js`, `lib/`, `package.json`: the deploy kit",
    ]
    if has_backend:
        lines.append("- `BACKEND-CONTRACT.md`: the calls your API must answer")
    lines += [
        "- `WIRING-GUIDE.md`: adding the Agentic CX block to your Contact Flow",
        "",
        "## Deploy",
        "",
        "Requirements: Node.js 20+, a Connect Customer instance with an Agentic CX designer",
        "workspace, and a programmatic API key (Admin Hub > Users > API access).",
        "",
        "```bash",
        "./deploy.sh --dry-run     # the plan, nothing changes",
        "export ACXD_WORKSPACE_ID=<workspace id> ACXD_API_KEY=<acxd_live_...>",
    ]
    if has_backend:
        default = backend.get("base_url") or "https://api.example.com"
        lines.append(f"export WEBHOOK_URL={default}   # base URL of your backend API")
        if backend.get("auth_header"):
            lines.append("export ACXD_SECRET_BACKENDAPIKEY=<value of the "
                         f"{backend['auth_header']} header>")
    lines += [
        "./deploy.sh               # prompts for anything not exported",
        "./deploy.sh status",
        "./deploy.sh cleanup",
        "```",
        "",
        "The deploy is idempotent: re-running updates the same resources. The API key and",
        "secret values are read from the environment and never written into the bundle or",
        "its state files.",
        "",
        "Next: `WIRING-GUIDE.md`.",
        "",
    ]
    return "\n".join(lines)


@tool
def package_and_upload_assets(
    session_id: str,
    project_name: str = "aicc-poc",
    include_readme: bool = True,
) -> dict:
    """Strands tool wrapper — see package_assets_impl for implementation."""
    return package_assets_impl(session_id, project_name, include_readme, asset_type_filter=None)


def _session_project_name(session_id: str) -> Optional[str]:
    """The ASCII project name an ACXD-only session recorded, or None.

    The download endpoint calls the packager without one, so every bundle was
    named 'aicc-poc' (live, SELC ACXD only, 2026-09-26: folder, README title and
    manifest said aicc-poc while the application was selc-voice, and two
    downloads unpacked into the same folder)."""
    try:
        from tools.acxd_flow_spec import derived_project_name, get_acxd_flow_spec
        spec = get_acxd_flow_spec(session_id)
        app = getattr(spec, "application", None) if spec is not None else None
        return derived_project_name(app) if app is not None else None
    except Exception as e:  # pragma: no cover - best effort, never blocks a download
        logger.debug(f"[packager] ACXD project name unavailable for {session_id}: {e}")
        return None


def package_assets_impl(
    session_id: str,
    project_name: str = "aicc-poc",
    include_readme: bool = True,
    asset_type_filter: Optional[str] = None,
) -> dict:
    """
    Package all generated assets from S3 into a ZIP file and upload to S3.

    This tool collects all assets that were generated by Sub-Agents during the session,
    packages them into a downloadable ZIP file with proper folder structure,
    uploads to S3, and returns a presigned URL for download.

    The ZIP structure follows the workshop guide conventions:
    - cloudformation/infrastructure.yaml - Complete CloudFormation template
    - lambda/{operation_id}/index.py - Lambda handler code (reference/modify)
    - openapi/openapi.yaml - OpenAPI specification
    - prompts/ai_agent_prompt.yaml - AI agent prompt
    - contact-flow/contact_flow.json - Contact flow
    - knowledge-base/{category}/*.txt - FAQ documents (optional)

    Args:
        session_id: Unique session identifier (used for S3 key)
        project_name: Name for the project folder in the ZIP
        include_readme: Include README with deployment instructions

    Returns:
        - download_url: Presigned S3 URL (valid for 24 hours)
        - expires_at: URL expiration timestamp
        - file_list: List of files included in the ZIP
        - total_size_bytes: Total size of the ZIP file
        - assets_found: Summary of what was found per asset type
    """
    bucket_name = get_bucket_name()
    if not bucket_name:
        # Try alternate environment variable
        bucket_name = os.environ.get("ASSETS_BUCKET")

    if (not project_name or project_name == "aicc-poc") and _is_acxd_only_target(session_id):
        # ACXD only has no CloudFormation stack whose name follows the project,
        # so the bundle can carry the application's own project name. The other
        # targets keep their default: the runner names '<project>-stack' after it.
        project_name = _session_project_name(session_id) or "aicc-poc"

    if not bucket_name:
        return {
            "success": False,
            "error": "ASSETS_BUCKET or ASSETS_BUCKET_NAME environment variable not configured"
        }

    try:
        # Package directly from S3, bypassing the NFS fast-path. The mount
        # (mountpoint-s3) caches directory metadata and recently-read object
        # content for several seconds; during an active edit session that
        # cache can shadow writes that have already been committed to S3,
        # causing the ZIP to contain first-generation content even though S3
        # versioning and the live preview show the new content. The NFS
        # fast-path is correct for agent-in-loop reads that tolerate the
        # cache window, but download handoff must read through S3.
        s3_keys = list_session_assets(session_id, s3_only=True)
        if not s3_keys:
            return {
                "success": False,
                "error": "No assets found for this session. Generate some assets first using the AI builder.",
                "session_id": session_id
            }
        parsed_assets = _parse_s3_keys(s3_keys)

        # Optional filter by asset type (matches raw type or its mapped folder name)
        if asset_type_filter:
            needle = asset_type_filter.lower()
            target_folder = ASSET_TYPE_FOLDER_MAP.get(needle, needle)
            if needle in ACXD_DOWNLOAD_ALIASES:
                # The whole ACXD application (flows, slot types, data requests, …).
                parsed_assets = {
                    k: v for k, v in parsed_assets.items()
                    if v["asset_type"].lower() in ACXD_STORAGE_TYPES
                }
            else:
                parsed_assets = {
                    k: v for k, v in parsed_assets.items()
                    if v["asset_type"].lower() == needle
                    or ASSET_TYPE_FOLDER_MAP.get(v["asset_type"].lower(), v["asset_type"].lower()) == target_folder
                }
            if not parsed_assets:
                return {
                    "success": False,
                    "error": f"No assets found for type '{asset_type_filter}'.",
                    "session_id": session_id,
                }

        logger.info(
            f"[packager] Packaging session {session_id} from S3 "
            f"({len(s3_keys)} keys, {len(parsed_assets)} parsed)"
        )

        acxd_plan = None
        if not asset_type_filter and _is_acxd_target(session_id):
            try:
                acxd_bundle, acxd_manifest, acxd_problems = _prepare_acxd_package(
                    session_id, project_name)
            except Exception:
                logger.exception("[packager] unable to prepare ACXD package")
                return {
                    "success": False,
                    "error": "ACXD packaging refused: the D9/manifest validation could not run; "
                             "see the server log for details.",
                    "session_id": session_id,
                }
            if acxd_problems:
                return {
                    "success": False,
                    "error": "ACXD packaging refused:\n- " + "\n- ".join(acxd_problems),
                    "problems": acxd_problems,
                    "session_id": session_id,
                }
            acxd_plan = (acxd_bundle, acxd_manifest)
        # ACXD only (v3.1): the archive is the ACXD application and its deploy
        # kit. Nothing Classic is generated, and a stray asset (an FAQ source
        # file, an import) must not make the bundle look like a Classic one.
        acxd_only = bool(acxd_plan) and _is_acxd_only_target(session_id)
        backend_settings = _acxd_only_backend_settings(session_id) if acxd_only else {}

        # Create in-memory ZIP file
        zip_buffer = io.BytesIO()
        file_list = []
        assets_found = {}

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            zip_paths: set[str] = set()
            # archive path → sha256 of what was written there. The preview
            # stream saves some documents twice (`<type>/<file>` and
            # `<type>/<id>/<file>`, live: research/research.json); an identical
            # second copy is the same file and is skipped — only a DIFFERENT
            # document at the same path makes the bundle ambiguous.
            zip_digests: dict[str, str] = {}
            for s3_key, asset_info in ({} if acxd_only else parsed_assets).items():
                asset_type = asset_info["asset_type"]
                operation_id = asset_info.get("operation_id")
                file_name = asset_info["file_name"]

                # Target-specific assets are written below from load_acxd_bundle;
                # prompts are intentionally absent for the ACXD runtime target.
                if acxd_plan and (asset_type.lower() in ACXD_STORAGE_TYPES
                                  or asset_type.lower() in {"prompt", "contact_flow", "contactflow", "contact-flow"}):
                    continue

                content = get_asset_from_s3(s3_key, s3_only=True)
                if not content:
                    logger.warning(f"[packager] empty/unreadable S3 asset: {s3_key}")
                    continue

                # ACXD delivers built-in slot values without separators (live:
                # 010-1111-2222 → 01011112222); the handler validates the spec
                # format. Wrap every ACXD bundle's Python handler so the
                # OperationSpec formats are restored before validation.
                if acxd_plan and asset_type.lower() == "lambda" and file_name.endswith(".py") \
                        and operation_id:
                    patterns = _acxd_field_patterns(operation_id)
                    # The interview often records the format only on the flow's
                    # slot (appointmentDate ^\d{4}-\d{2}-\d{2}$) and not on the
                    # OperationSpec field: the payload mapping says which slot
                    # feeds which request field.
                    for name, pattern in _acxd_slot_patterns(acxd_plan[0], operation_id).items():
                        patterns.setdefault(name, pattern)
                    try:
                        from tools.acxd_lambda_adapter import inject as _inject_adapter
                        new_content, restored = _inject_adapter(
                            content if isinstance(content, str) else content.decode("utf-8"), patterns,
                            response_types=_acxd_response_types(acxd_plan[0], operation_id),
                            request_types=_acxd_request_types(acxd_plan[0], operation_id))
                        if restored:
                            content = new_content
                            logger.info(f"[packager] {operation_id}: ACXD boundary adapter added ({restored})")
                    except Exception as exc:  # pragma: no cover - never block packaging on the aid
                        logger.warning(f"[packager] {operation_id}: ACXD boundary adapter skipped: {exc}")

                if asset_type.lower() in ACXD_STORAGE_TYPES:
                    # Filtered ACXD download: keep the deployment layout so the
                    # folder can be dropped into a bundle as-is.
                    zip_path = _acxd_asset_zip_path(project_name, asset_type, file_name)
                else:
                    zip_path = _get_zip_path(
                        project_name=project_name,
                        asset_type=asset_type,
                        file_name=file_name,
                        operation_id=operation_id
                    )

                if zip_path:
                    digest = hashlib.sha256(
                        content if isinstance(content, bytes) else str(content).encode("utf-8")).hexdigest()
                    if zip_path in zip_paths:
                        if zip_digests.get(zip_path) == digest:
                            logger.info(f"[packager] identical duplicate copy skipped: {s3_key} -> {zip_path}")
                            continue
                        if acxd_plan:
                            _refuse(
                                f"duplicate archive path {zip_path!r} with different content "
                                f"({s3_key}); refusing an ambiguous ACXD bundle")
                    zf.writestr(zip_path, content)
                    zip_paths.add(zip_path)
                    zip_digests[zip_path] = digest
                    file_list.append(zip_path)

                    if asset_type not in assets_found:
                        assets_found[asset_type] = []
                    assets_found[asset_type].append(file_name)

            if acxd_plan:
                acxd_bundle, acxd_manifest = acxd_plan
                for relative_path, payload, executable in build_acxd_zip_entries(
                        project_name, acxd_bundle, acxd_manifest, external_backend=acxd_only):
                    zip_path = f"{project_name}/{relative_path}"
                    if zip_path in zip_paths:
                        _refuse(
                            f"duplicate archive path {zip_path!r}; refusing an ambiguous ACXD bundle")
                    zf.writestr(zip_path, payload)
                    if executable:
                        zf.getinfo(zip_path).external_attr = 0o755 << 16
                    zip_paths.add(zip_path)
                    file_list.append(zip_path)

                backend_problems = _manifest_file_problems(
                    acxd_manifest,
                    {item[len(project_name) + 1:] for item in zip_paths
                     if item.startswith(f"{project_name}/")},
                )
                if backend_problems:
                    _refuse(
                        "ACXD bundle is missing manifest-referenced backend assets:\n  - "
                        + "\n  - ".join(backend_problems))

            # Add README with deployment instructions
            if include_readme and file_list:
                if acxd_only:
                    readme_content = _generate_acxd_only_readme(
                        project_name, acxd_plan[0], acxd_plan[1], backend_settings)
                else:
                    readme_content = _generate_readme(
                        project_name=project_name,
                        assets_found=assets_found
                    )
                    if acxd_plan:
                        readme_content += "\n\n" + _generate_acxd_readme_section() + "\n"
                readme_path = f"{project_name}/README.md"
                zf.writestr(readme_path, readme_content)
                zip_paths.add(readme_path)
                file_list.append(readme_path)

            # Add deploy.sh for CloudShell one-click deployment (from template).
            # ACXD only ships its own short script: the runner and nothing else.
            if file_list:
                template_path = os.path.join(
                    os.path.dirname(__file__), "..", "templates",
                    ACXD_ONLY_DEPLOY_TEMPLATE if acxd_only else "deploy_workshop.sh",
                )
                if os.path.exists(template_path):
                    with open(template_path, "r") as f:
                        deploy_script = f.read()
                else:
                    deploy_script = None
                if acxd_only and not deploy_script:
                    _refuse("the ACXD-only deploy script template is missing from this build")
                if deploy_script:
                    deploy_path = f"{project_name}/deploy.sh"
                    zf.writestr(deploy_path, deploy_script,
                                compress_type=zipfile.ZIP_DEFLATED)
                    # Set executable permission via external_attr
                    info = zf.getinfo(deploy_path)
                    info.external_attr = 0o755 << 16
                    zip_paths.add(deploy_path)
                    file_list.append(deploy_path)

            if acxd_plan:
                wiring_path = f"{project_name}/WIRING-GUIDE.md"
                zf.writestr(wiring_path, _generate_acxd_only_wiring_guide(acxd_plan[0]) if acxd_only
                            else _generate_wiring_guide(acxd_plan[0]))
                zip_paths.add(wiring_path)
                file_list.append(wiring_path)
            if acxd_only and _external_data_requests(acxd_plan[0]):
                contract_path = f"{project_name}/BACKEND-CONTRACT.md"
                zf.writestr(contract_path, _generate_backend_contract(acxd_plan[0], backend_settings))
                zip_paths.add(contract_path)
                file_list.append(contract_path)

        # Check if we actually packaged anything
        if not file_list:
            return {
                "success": False,
                "error": "No valid assets could be retrieved from S3.",
                "session_id": session_id,
                "s3_keys_found": len(s3_keys)
            }

        # Get ZIP size
        zip_buffer.seek(0, 2)  # Seek to end
        total_size = zip_buffer.tell()
        zip_buffer.seek(0)  # Reset to beginning

        # Upload to S3 (include filter/type in key so types don't overwrite each other)
        # The DOWNLOAD filename also carries the timestamp so successive downloads
        # are distinguishable on disk (previously every download landed as the
        # same `{project_name}.zip`, which is not scalable across iterations).
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        type_tag = f"-{asset_type_filter}" if asset_type_filter else ""
        # Sanitize project_name for use in a filename (spaces/slashes → hyphen).
        safe_project = re.sub(r'[^A-Za-z0-9._-]+', '-', (project_name or "aicc-poc")).strip('-') or "aicc-poc"
        s3_key = f"packages/{session_id}/{safe_project}{type_tag}-{timestamp}.zip"
        download_filename = f"{safe_project}{type_tag}-{timestamp}.zip"

        s3_client = get_s3_client()
        s3_client.upload_fileobj(
            zip_buffer,
            bucket_name,
            s3_key,
            ExtraArgs={
                "ContentType": "application/zip",
                "Metadata": {
                    "session-id": session_id,
                    "project-name": project_name,
                    "created-at": datetime.now(timezone.utc).isoformat(),
                    "file-count": str(len(file_list))
                }
            }
        )

        # Generate presigned URL
        presigned_url = s3_client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": bucket_name,
                "Key": s3_key,
                'ResponseContentDisposition': f'attachment; filename="{download_filename}"'
            },
            ExpiresIn=DEFAULT_EXPIRATION_SECONDS
        )

        expires_at = datetime.now(timezone.utc).timestamp() + DEFAULT_EXPIRATION_SECONDS
        expires_at_iso = datetime.fromtimestamp(expires_at, tz=timezone.utc).isoformat()

        return {
            "success": True,
            "download_url": presigned_url,
            "expires_at": expires_at_iso,
            "expires_in_hours": 24,
            "file_list": file_list,
            "file_count": len(file_list),
            "total_size_bytes": total_size,
            "total_size_mb": round(total_size / (1024 * 1024), 2),
            "s3_key": s3_key,
            "assets_found": assets_found,
            "runtime_target": "acxd_only" if acxd_only else ("acxd" if acxd_plan else "classic"),
            "message": f"Assets packaged successfully! {len(file_list)} files, {round(total_size / 1024, 1)} KB"
        }

    except ACXDPackagingError:
        # A refusal this module raised on purpose; its wording was recorded for the user.
        return {"success": False, "error": _LAST_REFUSAL.get() or "ACXD packaging refused."}
    except ClientError:
        logger.exception("[packager] S3 operation failed")
        return {
            "success": False,
            "error": "S3 operation failed; see the server log for details."
        }
    except Exception:
        logger.exception("[packager] failed to package assets")
        return {
            "success": False,
            "error": "Failed to package assets; see the server log for details."
        }


def _parse_s3_keys(s3_keys: list) -> dict:
    """
    Parse S3 keys to extract asset information.

    S3 key format: assets/{session_id}/{asset_type}/{operation_id}/{file_name}
                   or assets/{session_id}/{asset_type}/{file_name}

    Args:
        s3_keys: List of S3 key paths

    Returns:
        Dictionary mapping S3 key to asset info
    """
    parsed = {}

    for key in s3_keys:
        parts = key.split("/")

        # Expected: assets/session_id/asset_type/[operation_id/]file_name
        if len(parts) < 4 or parts[0] != "assets":
            continue

        # Extract components
        # parts[0] = "assets"
        # parts[1] = session_id
        # parts[2] = asset_type
        # parts[3] = operation_id or file_name
        # parts[4] = file_name (if operation_id present)

        asset_type = parts[2]

        if len(parts) == 4:
            # No operation_id: assets/session/type/filename
            operation_id = None
            file_name = parts[3]
        elif len(parts) == 5:
            # With operation_id: assets/session/type/op_id/filename
            operation_id = parts[3]
            file_name = parts[4]
        else:
            # Nested structure for FAQ categories: assets/session/faq/category/filename
            operation_id = parts[3]  # Category name
            file_name = parts[-1]

        parsed[key] = {
            "asset_type": asset_type,
            "operation_id": operation_id,
            "file_name": file_name
        }

    return parsed


def _get_zip_path(
    project_name: str,
    asset_type: str,
    file_name: str,
    operation_id: Optional[str] = None
) -> Optional[str]:
    """
    Determine the ZIP path for an asset.

    Args:
        project_name: Project name for the root folder
        asset_type: Type of asset
        file_name: Name of the file
        operation_id: Optional operation identifier

    Returns:
        ZIP path or None if asset type is unknown
    """
    # Get folder from mapping
    folder = ASSET_TYPE_FOLDER_MAP.get(asset_type.lower())

    if not folder:
        # Unknown asset type, try to use it as-is
        folder = asset_type.lower()

    # Build path based on asset type
    if asset_type.lower() in ("lambda",):
        # Lambda functions need operation_id subfolder
        if operation_id:
            return f"{project_name}/{folder}/{operation_id}/{file_name}"
        else:
            return f"{project_name}/{folder}/{file_name}"

    elif asset_type.lower() in ("faq", "knowledge_base", "knowledge-base"):
        # Knowledge base files use category (operation_id) as subfolder
        if operation_id:
            return f"{project_name}/{folder}/{operation_id}/{file_name}"
        else:
            return f"{project_name}/{folder}/{file_name}"

    elif asset_type.lower() == "prompt":
        # Normalize prompt filename to ai_agent_prompt.yaml for workshop consistency
        return f"{project_name}/{folder}/ai_agent_prompt.yaml"

    else:
        # Other asset types go directly into their folder
        return f"{project_name}/{folder}/{file_name}"


def _generate_readme(
    project_name: str,
    assets_found: dict
) -> str:
    """Generate README.md with deployment instructions based on what was actually generated."""

    sections = []

    # Header
    sections.append(f"""# {project_name}

**AI Contact Center POC Assets**

Generated by AICC Builder on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}

---

## 📦 Included Assets

""")

    # List what's included
    asset_descriptions = {
        "cloudformation": "CloudFormation infrastructure template",
        "infrastructure": "CloudFormation infrastructure template",
        "lambda": "Lambda function handlers",
        "openapi": "OpenAPI 3.0 specification",
        "prompt": "AI agent prompt for Amazon Connect",
        "contact_flow": "Amazon Connect Contact Flow",
        "contactflow": "Amazon Connect Contact Flow",
        "faq": "Knowledge Base FAQ documents",
        "knowledge_base": "Knowledge Base FAQ documents",
    }

    for asset_type, files in assets_found.items():
        desc = asset_descriptions.get(asset_type.lower(), asset_type)
        sections.append(f"- **{desc}**: {len(files)} file(s)\n")

    sections.append("\n---\n")

    # CloudFormation section (if present)
    if any(t.lower() in ("cloudformation", "infrastructure") for t in assets_found.keys()):
        sections.append("""
## 🚀 Quick Start: CloudFormation Deployment (Recommended)

### Option 1: One-Click Deployment with deploy.sh (CloudShell)

The easiest way to deploy is using the included `deploy.sh` script in AWS CloudShell:

```bash
# 1. Upload the assets ZIP to CloudShell
# 2. Extract and run:
unzip """ + project_name + """.zip && cd """ + project_name + """
chmod +x deploy.sh && ./deploy.sh
```

The script automatically (13 phases, idempotent — safe to re-run):
- ✅ Asks for a deployment name (stack/resource prefix) so multiple PoCs can coexist
- ✅ Deploys the CloudFormation stack (S3 upload for large templates)
- ✅ Updates all Lambda function code + uploads OpenAPI spec / FAQ documents
- ✅ Creates/selects the Amazon Connect instance (interactive menu) and enables
  the required instance attributes (incl. `BOT_MANAGEMENT` so Lex bots are
  manageable from the Connect console Flows > Bots tab)
- ✅ Creates the Q in Connect Assistant + Knowledge Base
- ✅ Injects env vars into the update-q-session Lambda AND grants its role the
  runtime permissions it needs (`connect:DescribeContact` + `wisdom:UpdateSessionData`)
  — without these the AI agent can't see the caller's phone number
- ✅ Creates the AgentCore Gateway (MCP server) and fixes the JWT audience
- ✅ Registers the MCP server with Connect + associates Lambda functions
- ✅ Creates the Lex bot with the Connect-assistant link
  (`AMAZON.QInConnectIntent` bound to the assistant ARN — backfilled on
  existing bots too) and your choice of speech model:
  Nova Sonic speech-to-speech / agentic-voice Advanced ASR / standard
- ✅ Lets you pick the voice provider: **Amazon Connect agentic voice**
  (expressive, 50+ languages — flow ships with a working Polly fallback and the
  summary prints the ~1-min console step to switch the Set voice block's
  provider) or **Amazon Polly** (voice + engine fully selected in the script)
- ✅ Imports the Contact Flow with all placeholders auto-resolved
- ✅ Creates the AI Prompt + AI Agent, attaches the security profile with
  per-tool MCP permissions, and **verifies the attachment via the API**
  (an unattached profile = every tool call fails with "Tool is not allowed")
- ✅ Optionally claims a US phone number and attaches it to the flow

Every decision point is an interactive multiple-choice prompt (language, voice
provider, speech model, ASR tuning, model, queue, phone number, ...), with
options listed live from your account via the AWS CLI. A full transcript is
saved to `aicc_deploy_*.log`. Run `./deploy.sh status` to inspect the
deployment and `./deploy.sh cleanup` to tear everything down.

### Option 2: Manual Deployment

If your template is > 51KB, you must upload it to S3 first:

```bash
# Create S3 bucket for templates
BUCKET=""" + project_name + """-cfn-templates-$(aws sts get-caller-identity --query Account --output text)"
aws s3 mb "s3://$BUCKET" --region ap-northeast-2

# Upload template
aws s3 cp cloudformation/infrastructure.yaml "s3://$BUCKET/infrastructure.yaml"

# Deploy using S3 URL
aws cloudformation deploy \\
  --template-url "https://$BUCKET.s3.ap-northeast-2.amazonaws.com/infrastructure.yaml" \\
  --stack-name """ + project_name + """-dev \\
  --parameter-overrides ProjectName=""" + project_name + """ Environment=dev \\
  --capabilities CAPABILITY_NAMED_IAM \\
  --region ap-northeast-2
```

For templates < 51KB, you can use `--template-file` instead of `--template-url`.

### What Gets Deployed

- **DynamoDB Table** with indexes (phone-index, status-date-index)
- **Lambda Functions** for each operation (inline code)
- **API Gateway REST API** with CORS enabled
- **IAM Roles** with least-privilege access
- **Sample Data** seeded via Custom Resource

### Important Outputs

| Output | Description | Usage |
|--------|-------------|-------|
| `ApiEndpoint` | API Gateway URL | Update OpenAPI spec's `servers` URL |
| `TableName` | DynamoDB table name | Reference for debugging |

""")

    # Lambda section (if present)
    if "lambda" in assets_found:
        sections.append("""
## 📁 Lambda Functions (Reference)

The `lambda/` folder contains individual handler files for reference or modification.

> **Note**: If you used `deploy.sh`, Lambda functions are automatically updated.
> Otherwise, you can manually update them using the AWS CLI after CloudFormation deployment.

### Handler Entry Points
- **Python Lambdas**: `index.lambda_handler` (standard AWS convention)
- **Node.js Lambdas** (update_q_session): `index.handler`

### Manual Update (if not using deploy.sh)

```bash
# Update a specific Lambda function
cd lambda/check_reservation
zip -j /tmp/lambda.zip index.py
aws lambda update-function-code \\
  --function-name """ + project_name + """-dev-check-reservation \\
  --zip-file fileb:///tmp/lambda.zip \\
  --region ap-northeast-2
```

```
lambda/
""")
        for file_name in assets_found.get("lambda", []):
            sections.append(f"├── {file_name}\n")
        sections.append("```\n")

    # OpenAPI section (if present)
    if "openapi" in assets_found:
        sections.append("""
## 📋 OpenAPI Specification

The `openapi/openapi.yaml` file is used to configure MCP Gateway in Amazon Connect.

### Important: Update Server URL

After CloudFormation deployment, update the `servers` section with your actual API Gateway URL:

```yaml
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-2.amazonaws.com/prod
```

### Usage in Amazon Connect

1. Navigate to Amazon Connect Console
2. Go to **MCP Gateway** settings
3. Upload or paste the OpenAPI spec
4. Configure authentication if required

""")

    # AI Prompt section (if present)
    if "prompt" in assets_found:
        sections.append("""
## 🤖 AI Agent Prompt

The `prompts/ai_agent_prompt.yaml` contains the system prompt for Amazon Connect's AI agent.

### Usage in Amazon Connect

1. Go to Amazon Connect Console
2. Navigate to **AI Agent** settings
3. Paste the content of `ai_agent_prompt.md` into the system prompt field
4. Save and test

""")

    # Contact Flow section (if present)
    if any(t.lower() in ("contact_flow", "contactflow", "contact-flow") for t in assets_found.keys()):
        sections.append("""
## 📞 Contact Flow

The `contact-flow/contact_flow.json` can be imported into Amazon Connect.

### Import Steps

1. Go to Amazon Connect Console
2. Navigate to **Contact Flows**
3. Click **Create contact flow** → **Import flow**
4. Select `contact_flow.json`
5. **Replace placeholders** before publishing:
   - `{{LEX_BOT_ALIAS_ARN}}` → Your Lex bot alias ARN
   - `{{QUEUE_ARN}}` → Your escalation queue ARN
6. Click **Publish**

""")

    # Knowledge Base section (if present)
    if any(t.lower() in ("faq", "knowledge_base", "knowledge-base") for t in assets_found.keys()):
        sections.append("""
## 📚 Knowledge Base FAQ

The `knowledge-base/` folder contains FAQ documents for Amazon Bedrock Knowledge Base.

### Upload to S3

```bash
# Upload all FAQ documents to your Knowledge Base bucket
aws s3 sync knowledge-base/ s3://YOUR-KB-BUCKET-NAME/faq/
```

### Sync Knowledge Base

After uploading, sync your Knowledge Base in the Amazon Bedrock console to index the new documents.

""")

    # Cleanup section
    sections.append("""
---

## 🧹 Cleanup

To delete all deployed resources:

```bash
aws cloudformation delete-stack \\
  --stack-name """ + project_name + """-dev \\
  --region ap-northeast-2

# Wait for deletion to complete
aws cloudformation wait stack-delete-complete \\
  --stack-name """ + project_name + """-dev \\
  --region ap-northeast-2
```

---

## 📖 Workshop Reference

For detailed instructions, refer to the workshop guide:
- Module 2: Infrastructure & MCP Server Setup
- Module 3: Knowledge Base Configuration
- Module 4: Contact Flow Setup

---

**Generated by AICC Builder** | Happy Building! 🎉
""")

    return "".join(sections)


