"""
Asset Packager Tool

Packages all generated assets from S3 into a ZIP file,
uploads to S3, and returns a presigned URL for download.

This module retrieves assets that were generated by Sub-Agents and saved to S3,
packages them into a downloadable ZIP with the following structure:

{project-name}/
├── README.md                    # Deployment guide
├── cloudformation/              # CloudFormation infrastructure (recommended)
│   └── infrastructure.yaml      # Complete infrastructure template
├── lambda/                      # Individual Lambda functions (reference/modify)
│   └── {operation_id}/
│       └── index.py           # Lambda handler code
├── openapi/
│   └── openapi.yaml             # OpenAPI 3.0 spec for MCP Gateway
├── prompts/
│   └── ai_agent_prompt.yaml       # Amazon Connect AI agent prompt
├── contact-flow/
│   └── contact_flow.json        # Importable contact flow
└── knowledge-base/              # Knowledge Base FAQ (optional)
    └── {category}/
        └── *.txt
"""

import io
import logging
import os
import zipfile
from datetime import datetime, timezone
from typing import Optional

from botocore.exceptions import ClientError
from strands import tool

from .s3_asset_storage import (
    list_session_assets,
    get_asset_from_s3,
    get_bucket_name,
    get_s3_client,
)

logger = logging.getLogger(__name__)


# Static update-q-session Lambda code (Node.js 18.x)
# Calls UpdateSessionData API to inject customer data into Q in Connect session.
# This is a generic proxy — business-specific fields are passed via Contact Flow LambdaInvocationAttributes.
UPDATE_Q_SESSION_LAMBDA_CODE = r"""const { QConnectClient, UpdateSessionDataCommand } = require('@aws-sdk/client-qconnect');
const { ConnectClient, DescribeContactCommand } = require('@aws-sdk/client-connect');

const qConnectClient = new QConnectClient();
const connectClient = new ConnectClient({ region: process.env.AWS_REGION });

const ContextKeys = {
  AI_ASSISTANT_ID: 'AI_ASSISTANT_ID',
  CONNECT_INSTANCE_ID: 'CONNECT_INSTANCE_ID',
};

const log = (level, message, data) => {
  const logEntry = { level, message };
  if (data) logEntry.params = data;
  console.log(JSON.stringify(logEntry));
};

const getAssistantSessionArn = async (contactId, connectInstanceId) => {
  const command = new DescribeContactCommand({
    ContactId: contactId,
    InstanceId: connectInstanceId,
  });
  const response = await connectClient.send(command);
  if (!response.Contact?.WisdomInfo?.SessionArn) {
    throw new Error(`No wisdom session found for contact ${contactId}.`);
  }
  return response.Contact.WisdomInfo.SessionArn;
};

const getKeyValuePairs = (connectRequest) => {
  const parameters = connectRequest.Details.Parameters;
  const reservedKeys = ['AI_ASSISTANT_ID', 'CONNECT_INSTANCE_ID'];
  const keyValuePairs = [];
  for (const [key, value] of Object.entries(parameters)) {
    if (!reservedKeys.includes(key) && value) {
      keyValuePairs.push({ key, value: { stringValue: String(value) } });
    }
  }
  return keyValuePairs;
};

exports.handler = async (connectRequest) => {
  log('INFO', 'Event', connectRequest);
  const contactId = connectRequest.Details.ContactData.ContactId;
  const aiAssistantId = connectRequest.Details.Parameters[ContextKeys.AI_ASSISTANT_ID]
    ?? process.env[ContextKeys.AI_ASSISTANT_ID];

  if (!contactId || !aiAssistantId) {
    throw new Error('Missing required parameters contactId or aiAssistantId');
  }

  const keyValuePairs = getKeyValuePairs(connectRequest);
  if (keyValuePairs.length === 0) {
    throw new Error('No key value pairs found');
  }

  const connectId = process.env[ContextKeys.CONNECT_INSTANCE_ID];
  if (!connectId) {
    throw new Error('No connect instance id found in environment variables');
  }

  const assistantSessionArn = await getAssistantSessionArn(contactId, connectId);
  const command = new UpdateSessionDataCommand({
    assistantId: aiAssistantId,
    sessionId: assistantSessionArn,
    data: keyValuePairs,
  });
  log('INFO', 'updateSessionCommand', command);
  await qConnectClient.send(command);

  return { statusCode: 200 };
};
"""


# Default presigned URL expiration: 24 hours
DEFAULT_EXPIRATION_SECONDS = 24 * 60 * 60


# Asset type to ZIP folder mapping
ASSET_TYPE_FOLDER_MAP = {
    "cloudformation": "cloudformation",
    "infrastructure": "cloudformation",  # Alias
    "cdk": "cloudformation",  # Legacy alias
    "lambda": "lambda",
    "openapi": "openapi",
    "prompt": "prompts",
    "contact_flow": "contact-flow",
    "contactflow": "contact-flow",  # Alias
    "contact-flow": "contact-flow",  # Alias
    "mermaid": "contact-flow",  # Mermaid diagrams go with contact flow
    "faq": "knowledge-base",
    "knowledge_base": "knowledge-base",  # Alias
    "knowledge-base": "knowledge-base",  # Alias
}


@tool
def package_and_upload_assets(
    session_id: str,
    project_name: str = "aicc-poc",
    include_readme: bool = True,
) -> dict:
    """Strands tool wrapper — see package_assets_impl for implementation."""
    return package_assets_impl(session_id, project_name, include_readme, asset_type_filter=None)


def package_assets_impl(
    session_id: str,
    project_name: str = "aicc-poc",
    include_readme: bool = True,
    asset_type_filter: Optional[str] = None,
) -> dict:
    """
    Package all generated assets from S3 into a ZIP file and upload to S3.

    This tool collects all assets that were generated by Sub-Agents during the session,
    packages them into a downloadable ZIP file with proper folder structure,
    uploads to S3, and returns a presigned URL for download.

    The ZIP structure follows the workshop guide conventions:
    - cloudformation/infrastructure.yaml - Complete CloudFormation template
    - lambda/{operation_id}/index.py - Lambda handler code (reference/modify)
    - openapi/openapi.yaml - OpenAPI specification
    - prompts/ai_agent_prompt.yaml - AI agent prompt
    - contact-flow/contact_flow.json - Contact flow
    - knowledge-base/{category}/*.txt - FAQ documents (optional)

    Args:
        session_id: Unique session identifier (used for S3 key)
        project_name: Name for the project folder in the ZIP
        include_readme: Include README with deployment instructions

    Returns:
        - download_url: Presigned S3 URL (valid for 24 hours)
        - expires_at: URL expiration timestamp
        - file_list: List of files included in the ZIP
        - total_size_bytes: Total size of the ZIP file
        - assets_found: Summary of what was found per asset type
    """
    bucket_name = get_bucket_name()
    if not bucket_name:
        # Try alternate environment variable
        bucket_name = os.environ.get("ASSETS_BUCKET")

    if not bucket_name:
        return {
            "success": False,
            "error": "ASSETS_BUCKET or ASSETS_BUCKET_NAME environment variable not configured"
        }

    try:
        # Package directly from S3, bypassing the NFS fast-path. The mount
        # (mountpoint-s3) caches directory metadata and recently-read object
        # content for several seconds; during an active edit session that
        # cache can shadow writes that have already been committed to S3,
        # causing the ZIP to contain first-generation content even though S3
        # versioning and the live preview show the new content. The NFS
        # fast-path is correct for agent-in-loop reads that tolerate the
        # cache window, but download handoff must read through S3.
        s3_keys = list_session_assets(session_id, s3_only=True)
        if not s3_keys:
            return {
                "success": False,
                "error": "No assets found for this session. Generate some assets first using the AI builder.",
                "session_id": session_id
            }
        parsed_assets = _parse_s3_keys(s3_keys)

        # Optional filter by asset type (matches raw type or its mapped folder name)
        if asset_type_filter:
            needle = asset_type_filter.lower()
            target_folder = ASSET_TYPE_FOLDER_MAP.get(needle, needle)
            parsed_assets = {
                k: v for k, v in parsed_assets.items()
                if v["asset_type"].lower() == needle
                or ASSET_TYPE_FOLDER_MAP.get(v["asset_type"].lower(), v["asset_type"].lower()) == target_folder
            }
            if not parsed_assets:
                return {
                    "success": False,
                    "error": f"No assets found for type '{asset_type_filter}'.",
                    "session_id": session_id,
                }

        logger.info(
            f"[packager] Packaging session {session_id} from S3 "
            f"({len(s3_keys)} keys, {len(parsed_assets)} parsed)"
        )

        # Create in-memory ZIP file
        zip_buffer = io.BytesIO()
        file_list = []
        assets_found = {}

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            for s3_key, asset_info in parsed_assets.items():
                asset_type = asset_info["asset_type"]
                operation_id = asset_info.get("operation_id")
                file_name = asset_info["file_name"]

                content = get_asset_from_s3(s3_key, s3_only=True)
                if not content:
                    logger.warning(f"[packager] empty/unreadable S3 asset: {s3_key}")
                    continue

                zip_path = _get_zip_path(
                    project_name=project_name,
                    asset_type=asset_type,
                    file_name=file_name,
                    operation_id=operation_id
                )

                if zip_path:
                    zf.writestr(zip_path, content)
                    file_list.append(zip_path)

                    if asset_type not in assets_found:
                        assets_found[asset_type] = []
                    assets_found[asset_type].append(file_name)

            # Add README with deployment instructions
            if include_readme and file_list:
                readme_content = _generate_readme(
                    project_name=project_name,
                    assets_found=assets_found
                )
                readme_path = f"{project_name}/README.md"
                zf.writestr(readme_path, readme_content)
                file_list.append(readme_path)

            # Add deploy.sh for CloudShell one-click deployment (from template)
            if file_list:
                template_path = os.path.join(
                    os.path.dirname(__file__), "..", "templates", "deploy_workshop.sh"
                )
                if os.path.exists(template_path):
                    with open(template_path, "r") as f:
                        deploy_script = f.read()
                else:
                    deploy_script = None
                if deploy_script:
                    deploy_path = f"{project_name}/deploy.sh"
                    zf.writestr(deploy_path, deploy_script,
                                compress_type=zipfile.ZIP_DEFLATED)
                    # Set executable permission via external_attr
                    info = zf.getinfo(deploy_path)
                    info.external_attr = 0o755 << 16
                    file_list.append(deploy_path)

        # Check if we actually packaged anything
        if not file_list:
            return {
                "success": False,
                "error": "No valid assets could be retrieved from S3.",
                "session_id": session_id,
                "s3_keys_found": len(s3_keys)
            }

        # Get ZIP size
        zip_buffer.seek(0, 2)  # Seek to end
        total_size = zip_buffer.tell()
        zip_buffer.seek(0)  # Reset to beginning

        # Upload to S3 (include filter/type in key so types don't overwrite each other)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        type_tag = f"-{asset_type_filter}" if asset_type_filter else ""
        s3_key = f"packages/{session_id}/{project_name}{type_tag}-{timestamp}.zip"
        download_filename = f"{project_name}{type_tag}.zip"

        s3_client = get_s3_client()
        s3_client.upload_fileobj(
            zip_buffer,
            bucket_name,
            s3_key,
            ExtraArgs={
                "ContentType": "application/zip",
                "Metadata": {
                    "session-id": session_id,
                    "project-name": project_name,
                    "created-at": datetime.now(timezone.utc).isoformat(),
                    "file-count": str(len(file_list))
                }
            }
        )

        # Generate presigned URL
        presigned_url = s3_client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": bucket_name,
                "Key": s3_key,
                'ResponseContentDisposition': f'attachment; filename="{download_filename}"'
            },
            ExpiresIn=DEFAULT_EXPIRATION_SECONDS
        )

        expires_at = datetime.now(timezone.utc).timestamp() + DEFAULT_EXPIRATION_SECONDS
        expires_at_iso = datetime.fromtimestamp(expires_at, tz=timezone.utc).isoformat()

        return {
            "success": True,
            "download_url": presigned_url,
            "expires_at": expires_at_iso,
            "expires_in_hours": 24,
            "file_list": file_list,
            "file_count": len(file_list),
            "total_size_bytes": total_size,
            "total_size_mb": round(total_size / (1024 * 1024), 2),
            "s3_key": s3_key,
            "assets_found": assets_found,
            "message": f"Assets packaged successfully! {len(file_list)} files, {round(total_size / 1024, 1)} KB"
        }

    except ClientError as e:
        return {
            "success": False,
            "error": f"S3 operation failed: {str(e)}"
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"Failed to package assets: {str(e)}"
        }


def _parse_s3_keys(s3_keys: list) -> dict:
    """
    Parse S3 keys to extract asset information.

    S3 key format: assets/{session_id}/{asset_type}/{operation_id}/{file_name}
                   or assets/{session_id}/{asset_type}/{file_name}

    Args:
        s3_keys: List of S3 key paths

    Returns:
        Dictionary mapping S3 key to asset info
    """
    parsed = {}

    for key in s3_keys:
        parts = key.split("/")

        # Expected: assets/session_id/asset_type/[operation_id/]file_name
        if len(parts) < 4 or parts[0] != "assets":
            continue

        # Extract components
        # parts[0] = "assets"
        # parts[1] = session_id
        # parts[2] = asset_type
        # parts[3] = operation_id or file_name
        # parts[4] = file_name (if operation_id present)

        asset_type = parts[2]

        if len(parts) == 4:
            # No operation_id: assets/session/type/filename
            operation_id = None
            file_name = parts[3]
        elif len(parts) == 5:
            # With operation_id: assets/session/type/op_id/filename
            operation_id = parts[3]
            file_name = parts[4]
        else:
            # Nested structure for FAQ categories: assets/session/faq/category/filename
            operation_id = parts[3]  # Category name
            file_name = parts[-1]

        parsed[key] = {
            "asset_type": asset_type,
            "operation_id": operation_id,
            "file_name": file_name
        }

    return parsed


def _get_zip_path(
    project_name: str,
    asset_type: str,
    file_name: str,
    operation_id: Optional[str] = None
) -> Optional[str]:
    """
    Determine the ZIP path for an asset.

    Args:
        project_name: Project name for the root folder
        asset_type: Type of asset
        file_name: Name of the file
        operation_id: Optional operation identifier

    Returns:
        ZIP path or None if asset type is unknown
    """
    # Get folder from mapping
    folder = ASSET_TYPE_FOLDER_MAP.get(asset_type.lower())

    if not folder:
        # Unknown asset type, try to use it as-is
        folder = asset_type.lower()

    # Build path based on asset type
    if asset_type.lower() in ("lambda",):
        # Lambda functions need operation_id subfolder
        if operation_id:
            return f"{project_name}/{folder}/{operation_id}/{file_name}"
        else:
            return f"{project_name}/{folder}/{file_name}"

    elif asset_type.lower() in ("faq", "knowledge_base", "knowledge-base"):
        # Knowledge base files use category (operation_id) as subfolder
        if operation_id:
            return f"{project_name}/{folder}/{operation_id}/{file_name}"
        else:
            return f"{project_name}/{folder}/{file_name}"

    elif asset_type.lower() == "prompt":
        # Normalize prompt filename to ai_agent_prompt.yaml for workshop consistency
        return f"{project_name}/{folder}/ai_agent_prompt.yaml"

    else:
        # Other asset types go directly into their folder
        return f"{project_name}/{folder}/{file_name}"


def _generate_readme(
    project_name: str,
    assets_found: dict
) -> str:
    """Generate README.md with deployment instructions based on what was actually generated."""

    sections = []

    # Header
    sections.append(f"""# {project_name}

**AI Contact Center POC Assets**

Generated by AICC Builder on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}

---

## 📦 Included Assets

""")

    # List what's included
    asset_descriptions = {
        "cloudformation": "CloudFormation infrastructure template",
        "infrastructure": "CloudFormation infrastructure template",
        "lambda": "Lambda function handlers",
        "openapi": "OpenAPI 3.0 specification",
        "prompt": "AI agent prompt for Amazon Connect",
        "contact_flow": "Amazon Connect Contact Flow",
        "contactflow": "Amazon Connect Contact Flow",
        "faq": "Knowledge Base FAQ documents",
        "knowledge_base": "Knowledge Base FAQ documents",
    }

    for asset_type, files in assets_found.items():
        desc = asset_descriptions.get(asset_type.lower(), asset_type)
        sections.append(f"- **{desc}**: {len(files)} file(s)\n")

    sections.append("\n---\n")

    # CloudFormation section (if present)
    if any(t.lower() in ("cloudformation", "infrastructure") for t in assets_found.keys()):
        sections.append("""
## 🚀 Quick Start: CloudFormation Deployment (Recommended)

### Option 1: One-Click Deployment with deploy.sh (CloudShell)

The easiest way to deploy is using the included `deploy.sh` script in AWS CloudShell:

```bash
# 1. Upload the assets ZIP to CloudShell
# 2. Extract and run:
unzip """ + project_name + """.zip && cd """ + project_name + """
chmod +x deploy.sh && ./deploy.sh
```

The script automatically:
- ✅ Uploads large templates to S3 (bypasses 51KB CloudFormation limit)
- ✅ Deploys infrastructure stack
- ✅ Updates all Lambda function code
- ✅ Uploads OpenAPI spec and FAQ documents
- ✅ Provides Contact Flow placeholder values

### Option 2: Manual Deployment

If your template is > 51KB, you must upload it to S3 first:

```bash
# Create S3 bucket for templates
BUCKET=""" + project_name + """-cfn-templates-$(aws sts get-caller-identity --query Account --output text)"
aws s3 mb "s3://$BUCKET" --region ap-northeast-2

# Upload template
aws s3 cp cloudformation/infrastructure.yaml "s3://$BUCKET/infrastructure.yaml"

# Deploy using S3 URL
aws cloudformation deploy \\
  --template-url "https://$BUCKET.s3.ap-northeast-2.amazonaws.com/infrastructure.yaml" \\
  --stack-name """ + project_name + """-dev \\
  --parameter-overrides ProjectName=""" + project_name + """ Environment=dev \\
  --capabilities CAPABILITY_NAMED_IAM \\
  --region ap-northeast-2
```

For templates < 51KB, you can use `--template-file` instead of `--template-url`.

### What Gets Deployed

- **DynamoDB Table** with indexes (phone-index, status-date-index)
- **Lambda Functions** for each operation (inline code)
- **API Gateway REST API** with CORS enabled
- **IAM Roles** with least-privilege access
- **Sample Data** seeded via Custom Resource

### Important Outputs

| Output | Description | Usage |
|--------|-------------|-------|
| `ApiEndpoint` | API Gateway URL | Update OpenAPI spec's `servers` URL |
| `TableName` | DynamoDB table name | Reference for debugging |

""")

    # Lambda section (if present)
    if "lambda" in assets_found:
        sections.append("""
## 📁 Lambda Functions (Reference)

The `lambda/` folder contains individual handler files for reference or modification.

> **Note**: If you used `deploy.sh`, Lambda functions are automatically updated.
> Otherwise, you can manually update them using the AWS CLI after CloudFormation deployment.

### Handler Entry Points
- **Python Lambdas**: `index.lambda_handler` (standard AWS convention)
- **Node.js Lambdas** (update_q_session): `index.handler`

### Manual Update (if not using deploy.sh)

```bash
# Update a specific Lambda function
cd lambda/check_reservation
zip -j /tmp/lambda.zip index.py
aws lambda update-function-code \\
  --function-name """ + project_name + """-dev-check-reservation \\
  --zip-file fileb:///tmp/lambda.zip \\
  --region ap-northeast-2
```

```
lambda/
""")
        for file_name in assets_found.get("lambda", []):
            sections.append(f"├── {file_name}\n")
        sections.append("```\n")

    # OpenAPI section (if present)
    if "openapi" in assets_found:
        sections.append("""
## 📋 OpenAPI Specification

The `openapi/openapi.yaml` file is used to configure MCP Gateway in Amazon Connect.

### Important: Update Server URL

After CloudFormation deployment, update the `servers` section with your actual API Gateway URL:

```yaml
servers:
  - url: https://xxxxxxxxxx.execute-api.ap-northeast-2.amazonaws.com/prod
```

### Usage in Amazon Connect

1. Navigate to Amazon Connect Console
2. Go to **MCP Gateway** settings
3. Upload or paste the OpenAPI spec
4. Configure authentication if required

""")

    # AI Prompt section (if present)
    if "prompt" in assets_found:
        sections.append("""
## 🤖 AI Agent Prompt

The `prompts/ai_agent_prompt.yaml` contains the system prompt for Amazon Connect's AI agent.

### Usage in Amazon Connect

1. Go to Amazon Connect Console
2. Navigate to **AI Agent** settings
3. Paste the content of `ai_agent_prompt.md` into the system prompt field
4. Save and test

""")

    # Contact Flow section (if present)
    if any(t.lower() in ("contact_flow", "contactflow", "contact-flow") for t in assets_found.keys()):
        sections.append("""
## 📞 Contact Flow

The `contact-flow/contact_flow.json` can be imported into Amazon Connect.

### Import Steps

1. Go to Amazon Connect Console
2. Navigate to **Contact Flows**
3. Click **Create contact flow** → **Import flow**
4. Select `contact_flow.json`
5. **Replace placeholders** before publishing:
   - `{{LEX_BOT_ALIAS_ARN}}` → Your Lex bot alias ARN
   - `{{QUEUE_ARN}}` → Your escalation queue ARN
6. Click **Publish**

""")

    # Knowledge Base section (if present)
    if any(t.lower() in ("faq", "knowledge_base", "knowledge-base") for t in assets_found.keys()):
        sections.append("""
## 📚 Knowledge Base FAQ

The `knowledge-base/` folder contains FAQ documents for Amazon Bedrock Knowledge Base.

### Upload to S3

```bash
# Upload all FAQ documents to your Knowledge Base bucket
aws s3 sync knowledge-base/ s3://YOUR-KB-BUCKET-NAME/faq/
```

### Sync Knowledge Base

After uploading, sync your Knowledge Base in the Amazon Bedrock console to index the new documents.

""")

    # Cleanup section
    sections.append("""
---

## 🧹 Cleanup

To delete all deployed resources:

```bash
aws cloudformation delete-stack \\
  --stack-name """ + project_name + """-dev \\
  --region ap-northeast-2

# Wait for deletion to complete
aws cloudformation wait stack-delete-complete \\
  --stack-name """ + project_name + """-dev \\
  --region ap-northeast-2
```

---

## 📖 Workshop Reference

For detailed instructions, refer to the workshop guide:
- Module 2: Infrastructure & MCP Server Setup
- Module 3: Knowledge Base Configuration
- Module 4: Contact Flow Setup

---

**Generated by AICC Builder** | Happy Building! 🎉
""")

    return "".join(sections)


