"""Shared consistency rules for every code-generator subagent prompt.

Issues #3/#4/#5 in debug/README.md traced drift between the infrastructure,
openapi, and lambda generators (CFN says POST while OpenAPI says GET; OpenAPI
omits /tools/ prefix; IAM policies use a non-existent qconnect:* namespace;
Architectures field dropped or spelled singular). A single shared rules block
prevents the three prompts from disagreeing with each other over time.

Every generator prompt imports CONSISTENCY_RULES and prepends it so these
rules appear before any example — the model follows the nearest example, so
rules MUST come before few-shot blocks, not after.
"""

CONSISTENCY_RULES = """
## 🔒 CROSS-GENERATOR GOLDEN RULES (SOURCE OF TRUTH — OBEY OVER EXAMPLES)

These rules bind the CloudFormation template, the OpenAPI spec, the Lambda
code, and the deploy.sh bundled in every generated ZIP. When any example
below appears to contradict a rule, the **RULES WIN**.

### 1. HTTP_METHOD_RULE
For every operation, the following three MUST be identical:
  - OperationSpec.http_method
  - OpenAPI operation verb (get / post / put / delete under the path)
  - CloudFormation AWS::ApiGateway::Method.HttpMethod
No exceptions, no "let's just accept both". If the spec says GET, every
artefact uses GET; if POST, every artefact uses POST.

### 2. PATH_PREFIX_RULE
  - OpenAPI `paths:` keys MUST begin with `/tools/`. Example: `/tools/check_reservation`.
  - CloudFormation `Outputs.ApiEndpoint` MUST be the stage root — `https://<id>.execute-api.<region>.amazonaws.com/<stage>` — with NO `/tools` suffix.
  - The deploy.sh that ships in the ZIP concatenates `ApiEndpoint` + the OpenAPI path. If OpenAPI omits `/tools/`, the Gateway returns 404. If CFN appends `/tools`, the URL doubles to `/tools/tools/...` and returns 403.

### 3. LAMBDA_ARCHITECTURES_RULE
Always block-list form, plural, exactly:

```yaml
Architectures:
  - arm64
```

NEVER use the singular `Architecture:` and NEVER use the inline flow-style
`Architectures: [arm64]`. CloudFormation only accepts the plural property;
the block-list form is the house style for this codebase.

### 4. IAM_Q_IN_CONNECT_RULE  (CRITICAL — fixes production AccessDenied)
The Amazon Q in Connect service is exposed in IAM under the `wisdom:*`
namespace. The `qconnect:*` namespace **does not exist as an IAM action
prefix** and will cause `AccessDenied` the moment the Lambda runs.

Rules:
  - **NEVER** emit an IAM action beginning with `qconnect:` in any
    Policy/PolicyDocument/Statement in the generated CloudFormation.
  - `QSessionUpdateLambda`'s execution role MUST include
    `wisdom:UpdateSessionData` (required) and may include
    `wisdom:GetSession` / `wisdom:ListSessions` as needed.
  - Note: the `aws qconnect ...` AWS CLI subcommand name IS correct (it's
    the CLI branding for Q in Connect). The rule above applies to IAM
    action strings inside CFN, not to CLI commands in shell scripts.

### 5. API_GATEWAY_PARENT_RULE
Every per-operation `AWS::ApiGateway::Resource` MUST use `!Ref ToolsResource`
as its `ParentId`. The template defines one `ToolsResource` whose parent is
`!GetAtt RestApi.RootResourceId` and whose `PathPart` is `tools`; every tool
hangs beneath it.

### 6. OPERATION_ID_CASING_RULE
`operation_id` is snake_case throughout (matching OperationSpec.operation_id).
Use it verbatim in OpenAPI path segments (`/tools/<operation_id>`). Derive
CFN logical IDs by PascalCasing it (`check_reservation` → `CheckReservation`).

### 7. OPENAPI_SERVERS_RULE
The OpenAPI `servers[0].url` MUST NOT include `/tools`. It is substituted at
deploy time from CFN's `ApiEndpoint`, which is the stage root. `/tools/` is
already part of each `paths:` key, so duplicating it here causes doubling.

### 8. LAMBDA_HANDLER_RULE
Default to `Handler: index.handler` and `Runtime: python3.12` unless the
OperationSpec explicitly requires otherwise. Keep this consistent with the
Lambda code generated by the lambda_generator (which writes `index.py` with
a top-level `handler(event, context)`).

### 9. OUTPUTS_API_ENDPOINT_RULE
Canonical form — use exactly this construction:

```yaml
Outputs:
  ApiEndpoint:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Description: API Gateway stage root. OpenAPI paths supply /tools/ prefix.
```

No `/tools` concatenated here. No trailing slash.

### 10. CFN_PARAMETER_CONSISTENCY
Every `!Ref <Name>` or `${Name}` reference inside the template must resolve
to either (a) a CFN pseudo-parameter (`AWS::Region`, `AWS::AccountId`,
`AWS::StackName`), (b) a `Parameters:` entry, or (c) a `Resources:` logical
ID defined in the same template. No free variables.

### 11. FEW_SHOT_TRUST_RULE
These rules override ANY few-shot example in this prompt. If an example
appears to violate a rule, treat the example as a legacy artefact and
follow the rule. Examples exist to show shape/structure, not to license
rule violations.

### 12. NO_QCONNECT_ACTIONS_ABSOLUTE
Repeating rule 4 because it recurs: do not emit `qconnect:` as an IAM
action prefix anywhere. Not in Statement.Action arrays, not in managed
policy references, not in inline policy strings, not in comments that
could be copied. Always `wisdom:` for Q in Connect / Wisdom actions.

### 13. FIELD_SHAPE_FIDELITY_RULE  (structural fidelity for nested data)
Whenever a spec field has `field_type` in ("array", "object"), the nested
shape MUST be preserved end-to-end. The spec's `items` / `properties` are
the source of truth for the element / sub-field schema:

  - `field_type="array"` + `items=<FieldSpec>`
      → OpenAPI: `type: array` with a non-empty `items:` block
      → Lambda: return `list[<items shape>]`
  - `field_type="object"` + `properties=[<FieldSpec>, ...]`
      → OpenAPI: `type: object` with a `properties:` dict whose keys match
        each sub-FieldSpec.name exactly
      → Lambda: return a `dict` whose keys match each sub-FieldSpec.name
  - `field_type="array"` + `items.field_type="object"` + `items.properties=[...]`
      → array of objects — emit `items:` as an object schema (or $ref)
        whose `properties:` keys mirror `items.properties[].name`.

**NEVER flatten** nested fields into sibling top-level fields. If the spec
says `machineStatus` is an array of `{machineType, state, remainingSeconds}`,
do NOT emit three sibling fields `machineType`, `state`, `remainingSeconds`
at the top level — emit `machineStatus` as an array-of-object.

**NEVER emit `type: array` with no `items:` block** — this is fatal; it
turns the tool into something the model can't call.

### 14. ENUM_FIDELITY_RULE
If a spec field has `enum_values` populated, those EXACT values — same
casing, same spelling, same order, same punctuation (underscores vs
hyphens matter) — must appear verbatim in OpenAPI `enum:` and in any
Lambda validation code (e.g., `if value not in {...}: return 400`).
Do NOT paraphrase, translate, abbreviate, or alphabetize. If the customer
supplied 18 Electrolux program modes, emit all 18 verbatim.

### 15. NESTED_OPENAPI_SCHEMA_RULE
OpenAPI nested schemas use `$ref` into `components/schemas` — named
component schemas for any nested object referenced more than once or
nested more than one level deep. Never inline a nested object past one
level; extract a named schema and reference it. Top-level request/response
schemas are always named (no anonymous top-level schemas).

### 16. LAMBDA_NESTED_RESPONSE_RULE
A Lambda handler whose spec has an array-of-objects output field MUST
produce the dict keys declared in `items.properties`, in the exact
camelCase spelled by the spec. Do NOT rename, flatten, or drop keys.
`event`-parsing and response-building must use the spec's nested field
names verbatim. For scalar output fields with `enum_values`, validate
against those exact values before returning.

## 🔒 END OF GOLDEN RULES — APPLY ALL OF THE ABOVE TO THE OUTPUT BELOW 🔒
"""


# =============================================================================
# Shared terminology + spec-escalation block for every generator sub-agent.
# Keep this SHORT — it prepends to every generator prompt.
# =============================================================================
SUBAGENT_TERMINOLOGY_AND_ESCALATION = """
## TERMINOLOGY FACTS (override model training)

- Product name in user-facing copy: **"Amazon Connect AI agents"**. Do NOT use
  the prior name "Amazon Q in Connect" in generated prompts, Play prompts,
  FAQ copy, or any other user-facing string.
- Code identifiers are EXEMPT and must NOT be renamed: leave
  `amazon-q-connect` namespaces, `CreateWisdomSession` flow action `Type`,
  `wisdom:*` IAM actions, and other SDK/API names intact.
- Configuration unit term: **"domain"** (not "Assistant Domain" /
  "AI Agent Domain"). One Amazon Connect instance → one domain.
- FAQ / Knowledge storage: the default path is **an S3 bucket registered
  as a Knowledge Source on the domain**. Bedrock Knowledge Base is only used
  when the user specifically asks (orchestration-type agents, on-contact).
  Do NOT tell the user their FAQ automatically goes into Bedrock KB.
- Nova Sonic integration with Amazon Connect voice is NOT a verified default
  — do not hard-code "built on Nova Sonic" into generated prompts unless the
  user specified it.

## SPEC-LEVEL MODIFICATION ESCALATION (applies when modification_request is set)

Before patching a file, classify the request:

- **Spec-level** = changes a domain rule that must survive regeneration:
  data model (field add/remove/rename), operating hours, slot granularity,
  retention, recording on/off, session greeting content, persona,
  identifier scheme.
- **Asset-level** = wording or presentation of this single file.

If the request is **spec-level**, DO NOT patch. Return this JSON as your
final message and stop:

    {"success": false,
     "escalation": "spec_level",
     "reason": "<which spec field/rule needs to change and why this file
               alone cannot own the change>",
     "suggested_spec_updates": ["<optional hints>"]}

The orchestrator will update the spec (`update_operation_spec` /
`save_infrastructure_spec` / `save_session_flow_config`), analyze
downstream impact, confirm with the user, and re-call you with a refined
request that you can then patch normally.

If the request is asset-level, proceed with the usual patch workflow.
"""


# =============================================================================
# Runtime field-schema section helper (shared by openapi + lambda generators).
#
# Renders a Markdown block describing every nested / enum / array field in the
# current session's OperationSpecs. Injected into the user prompt alongside
# the OperationSpec source-of-truth table so the model generates FROM the
# spec rather than guessing at the element/sub-field shape.
# =============================================================================

def _render_field_tree(field: dict, indent: int = 0) -> list:
    """Render one FieldSpec (as a dict) into Markdown tree lines.

    Only emits lines for fields that carry structural info worth showing:
    - nested `items` / `properties`
    - `enum_values`
    - declared `field_type` of array / object / enum
    Scalar fields with no enum are skipped at depth 0 (noise suppression)
    but always emitted when nested inside items/properties (context matters).
    """
    lines = []
    name = field.get("name", "?")
    ftype = (field.get("field_type") or field.get("type") or "string")
    enum_values = field.get("enum_values") or field.get("enum") or field.get("allowed_values") or field.get("options")
    items = field.get("items") or field.get("item") or field.get("element")
    properties = field.get("properties") or field.get("sub_fields") or field.get("fields")

    pad = "  " * indent
    suffix = ""
    if enum_values:
        # quote each value, join with comma
        vals = ", ".join(repr(v) for v in enum_values)
        suffix = f" (enum: {vals})"
    lines.append(f"{pad}- `{name}`: {ftype}{suffix}")

    if items is not None:
        lines.append(f"{pad}  items:")
        lines.extend(_render_field_tree(items, indent + 2))
    if properties:
        lines.append(f"{pad}  properties:")
        for sub in properties:
            lines.extend(_render_field_tree(sub, indent + 2))
    return lines


def _field_has_nested_structure(field: dict) -> bool:
    """True if this field carries nested / enum info worth surfacing."""
    if field.get("enum_values") or field.get("enum") or field.get("allowed_values") or field.get("options"):
        return True
    if field.get("items") or field.get("item") or field.get("element"):
        return True
    if field.get("properties") or field.get("sub_fields") or field.get("fields"):
        return True
    ftype = field.get("field_type") or field.get("type")
    if ftype in ("array", "object", "enum"):
        return True
    return False


def build_field_schema_section(ops_list: list) -> str:
    """Render the "NESTED FIELD SCHEMAS" source-of-truth section.

    Walks each OperationSpec (and any nested ToolSpecs), filters to fields
    with non-trivial structure, and renders them as a Markdown tree bound
    by FIELD_SHAPE_FIDELITY_RULE + ENUM_FIDELITY_RULE (rules 13 & 14).

    Returns "" if no operation has any nested/enum field — avoids adding
    noise to the prompt when the generation is purely scalar.
    """
    blocks: list = []

    for op in ops_list or []:
        op_id = op.get("operation_id") or op.get("tool_id") or ""

        def _emit_fields(owner_label: str, in_fields: list, out_fields: list) -> None:
            nonlocal blocks
            in_nested = [f for f in (in_fields or []) if _field_has_nested_structure(f)]
            out_nested = [f for f in (out_fields or []) if _field_has_nested_structure(f)]
            if not in_nested and not out_nested:
                return
            sect = [f"### {owner_label}"]
            if in_nested:
                sect.append("input_fields:")
                for f in in_nested:
                    sect.extend(_render_field_tree(f, indent=0))
            if out_nested:
                sect.append("output_fields:")
                for f in out_nested:
                    sect.extend(_render_field_tree(f, indent=0))
            blocks.append("\n".join(sect))

        # Operation-level fields
        if op_id:
            _emit_fields(
                f"operation: `{op_id}`",
                op.get("input_fields") or [],
                op.get("output_fields") or [],
            )

        # Tool-level fields (multi-tool operations)
        for t in op.get("tools") or []:
            tool_id = t.get("tool_id") or ""
            if not tool_id:
                continue
            _emit_fields(
                f"tool: `{tool_id}` (parent operation: `{op_id}`)",
                t.get("input_fields") or [],
                t.get("output_fields") or [],
            )

    if not blocks:
        return ""

    header = (
        "\n## 📋 NESTED FIELD SCHEMAS — SOURCE OF TRUTH FOR STRUCTURAL FIDELITY\n\n"
        "Every field below MUST round-trip verbatim into OpenAPI (items / "
        "properties / enum) and Lambda (dict keys / list element shapes / "
        "enum validation). Bound by rules 13 (FIELD_SHAPE_FIDELITY) and 14 "
        "(ENUM_FIDELITY). Flattening these into sibling top-level fields is "
        "a correctness bug.\n"
    )
    return header + "\n\n".join(blocks) + "\n"
